-- FinLit Zambia — Financial Character Simulator
-- 06-venture-income.sql  (safe to re-run)  Run AFTER 04.
--
-- Venture income is generated by the server, never typed in by the learner.
-- Every real day a venture is "open", it earns sales and pays running costs, and
-- may meet a problem or an opportunity. Those are DECISIONS for the learner
-- (see 07-venture-decisions.sql), not automatic losses. The next time the learner opens
-- the app, sim_collect_income() books everything into cash and the venture's
-- profit-and-loss. Up to 30 days of earnings are kept while away.
-- Profit is kept INSIDE the business (ventures.retained). The learner decides whether to
-- take it home, reinvest it, or leave it as a buffer (sim_venture_payout / a profit decision).

alter table ventures add column if not exists last_income_at timestamptz not null default now();

create table if not exists venture_category_rates (
  category text primary key,
  monthly_revenue_rate numeric(6,4) not null,  -- gross sales per GAME month, as a share of starting capital
  cost_ratio numeric(6,4) not null,            -- running costs as a share of sales
  volatility numeric(4,2) not null             -- how wildly sales swing from day to day
);

insert into venture_category_rates (category, monthly_revenue_rate, cost_ratio, volatility) values
  ('retail',      0.10, 0.72, 0.60),   -- steady, thin margins
  ('services',    0.11, 0.62, 0.50),   -- lower cost, steadier
  ('agriculture', 0.09, 0.75, 0.90),   -- big swings with weather and seasons
  ('tech',        0.12, 0.65, 0.80),   -- higher upside, higher variance
  ('other',       0.08, 0.75, 0.60)
on conflict (category) do update set
  monthly_revenue_rate = excluded.monthly_revenue_rate,
  cost_ratio = excluded.cost_ratio,
  volatility = excluded.volatility;

alter table venture_category_rates enable row level security;
drop policy if exists "read venture rates" on venture_category_rates;
create policy "read venture rates" on venture_category_rates for select using (true);
revoke insert, update, delete, truncate on venture_category_rates from anon, authenticated;

create or replace function sim_collect_income()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  v ventures; r venture_category_rates; e story_events; v_pay bigint;
  v_dpm numeric; v_elapsed numeric; v_days int; i int; v_f numeric; v_start timestamptz;
  v_cap numeric; v_eff numeric; v_rev numeric; v_cost numeric; v_newret numeric; v_hit boolean;
  t_rev numeric := 0; t_cost numeric := 0; t_days int := 0; t_events int := 0;
begin
  if uid is null then return jsonb_build_object('error', 'not_signed_in'); end if;
  v_dpm := story_game_months_to_days(1);          -- real days in one game month
  select id into v_pay from story_events where event_key = 'venture_profit_decision' and is_active;

  for v in select * from ventures where profile_id = uid and status = 'active' for update loop
    v_elapsed := extract(epoch from (now() - v.last_income_at)) / 86400.0;
    v_days := least(30, floor(v_elapsed)::int);
    if v_days < 1 then continue; end if;

    select * into r from venture_category_rates where category = v.category;
    if not found then select * into r from venture_category_rates where category = 'other'; end if;

    -- More capital earns more, but with diminishing returns beyond double the original
    -- (a business also needs people, customers and time, not just money).
    v_cap := coalesce(v.capital, v.starting_capital);
    v_eff := case when v_cap <= 2 * v.starting_capital then v_cap
                  else 2 * v.starting_capital + 0.5 * (v_cap - 2 * v.starting_capital) end;

    v_rev := 0; v_hit := false;
    for i in 1..v_days loop
      v_start := v.last_income_at + ((i - 1) * interval '1 day');
      v_f := 1 + (random() * 2 - 1) * r.volatility;
      if v.income_mult_until is not null and v_start < v.income_mult_until then v_f := v_f * v.income_mult; end if;
      v_rev := v_rev + v_eff * r.monthly_revenue_rate / v_dpm * v_f;
      -- 6% chance a day brings a problem or an opportunity; a guard (lock, cooling) cuts it by 70%
      if random() < 0.06 * (case when v.shock_guard_until is not null and v_start < v.shock_guard_until then 0.3 else 1 end) then
        v_hit := true;
      end if;
    end loop;

    v_rev := round(v_rev, 2);
    v_cost := round(v_rev * r.cost_ratio, 2);
    v_newret := v.retained + v_rev - v_cost;

    -- Profit stays INSIDE the business until the learner decides what to do with it.
    if v_rev > 0 then
      insert into venture_events (venture_id, kind, amount, description)
        values (v.id, 'revenue', v_rev, 'Sales over ' || v_days || (case when v_days = 1 then ' day' else ' days' end));
    end if;
    if v_cost > 0 then
      insert into venture_events (venture_id, kind, amount, description)
        values (v.id, 'expense', -v_cost, 'Running costs (stock, transport, wages)');
    end if;

    -- A problem or opportunity becomes a decision (not an automatic loss)
    if v_hit and not exists (
         select 1 from learner_pending_events pe join story_events se on se.id = pe.event_id
          where pe.profile_id = uid and pe.status = 'pending' and se.category = 'venture_event'
            and (pe.context->>'venture_id')::bigint = v.id) then
      select se.* into e from story_events se
       where se.category = 'venture_event' and se.is_active
         and (se.eligibility_config->'venture_categories' is null
              or se.eligibility_config->'venture_categories' ? v.category)
       order by random() limit 1;
      if e.id is not null then
        insert into learner_pending_events (profile_id, event_id, node_key, context)
        values (uid, e.id, e.entry_node,
                jsonb_build_object('venture_id', v.id, 'venture_name', v.name, 'capital', v_cap));
        t_events := t_events + 1;
      end if;
    end if;

    -- When enough profit has piled up, ask what to do with it
    if v_pay is not null and v_newret >= v_cap * 0.15 and not exists (
         select 1 from learner_pending_events pe
          where pe.profile_id = uid and pe.event_id = v_pay and (pe.context->>'venture_id')::bigint = v.id
            and (pe.status = 'pending' or pe.resolved_at > now() - interval '2 days')) then
      insert into learner_pending_events (profile_id, event_id, node_key, context)
      select uid, se.id, se.entry_node,
             jsonb_build_object('venture_id', v.id, 'venture_name', v.name, 'capital', v_cap,
                                'retained_text', 'K' || to_char(round(v_newret), 'FM999,999,990'))
        from story_events se where se.id = v_pay;
      t_events := t_events + 1;
    end if;

    update ventures
       set retained = v_newret,
           last_income_at = case when v_elapsed > 30 then now() else last_income_at + (v_days * interval '1 day') end
     where id = v.id;

    t_rev := t_rev + v_rev; t_cost := t_cost + v_cost; t_days := greatest(t_days, v_days);
  end loop;

  return jsonb_build_object('revenue', t_rev, 'costs', t_cost, 'shocks', 0,
                            'net', t_rev - t_cost, 'days', t_days, 'events', t_events);
end $$;

-- Pay yourself, reinvest, or put more of your own cash in. All amounts are checked here.
create or replace function sim_venture_payout(p_venture_id bigint, p_withdraw numeric, p_reinvest numeric, p_topup numeric)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid(); v ventures; v_cash numeric;
  w numeric := round(coalesce(p_withdraw, 0), 2); r numeric := round(coalesce(p_reinvest, 0), 2); t numeric := round(coalesce(p_topup, 0), 2);
begin
  if uid is null then return jsonb_build_object('error', 'not_signed_in'); end if;
  if w < 0 or r < 0 or t < 0 or w + r + t = 0 then return jsonb_build_object('error', 'bad_amount'); end if;
  select * into v from ventures where id = p_venture_id and profile_id = uid and status = 'active' for update;
  if not found then return jsonb_build_object('error', 'not_found'); end if;
  if w + r > v.retained then return jsonb_build_object('error', 'not_enough_profit', 'retained', v.retained); end if;
  select cash_balance into v_cash from profiles where id = uid for update;
  if t > v_cash + w then return jsonb_build_object('error', 'insufficient_cash', 'cash', v_cash + w); end if;

  if w > 0 then perform adjust_cash_balance(uid, w, 'venture_withdrawal', 'ventures', v.id); end if;
  if t > 0 then perform adjust_cash_balance(uid, -t, 'venture_topup', 'ventures', v.id); end if;
  update ventures set retained = retained - w - r, capital = coalesce(capital, starting_capital) + r + t where id = v.id;

  if w > 0 then insert into venture_events (venture_id, kind, amount, description) values (v.id, 'withdrawal', -w, 'Profit taken home'); end if;
  if r > 0 then insert into venture_events (venture_id, kind, amount, description) values (v.id, 'reinvest', -r, 'Profit reinvested in the business'); end if;
  if t > 0 then insert into venture_events (venture_id, kind, amount, description) values (v.id, 'topup', t, 'Extra cash invested'); end if;

  if r > 0 and w = 0 and not story_has_flag(uid, 'reinvested_profits') then perform story_set_flag(uid, 'reinvested_profits', null); end if;
  if w > 0 and r = 0 and not story_has_flag(uid, 'withdrew_profits') then perform story_set_flag(uid, 'withdrew_profits', null); end if;
  if w > 0 and r > 0 and not story_has_flag(uid, 'split_profits') then perform story_set_flag(uid, 'split_profits', null); end if;
  if t > 0 and not story_has_flag(uid, 'invested_own_cash') then perform story_set_flag(uid, 'invested_own_cash', null); end if;
  return jsonb_build_object('ok', true);
end $$;

-- Buy cover for a venture: pays a premium now, protects against theft and spoilage for one game year.
create or replace function sim_buy_cover(p_venture_id bigint)
returns jsonb language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); v ventures; v_prem numeric; v_cash numeric; v_days numeric;
begin
  if uid is null then return jsonb_build_object('error', 'not_signed_in'); end if;
  select * into v from ventures where id = p_venture_id and profile_id = uid and status = 'active' for update;
  if not found then return jsonb_build_object('error', 'not_found'); end if;
  if v.insured_until is not null and v.insured_until > now() then
    return jsonb_build_object('error', 'already_covered', 'until', v.insured_until);
  end if;
  -- people who know how insurance works shop around: 3% instead of 4% of capital
  v_prem := round(v.starting_capital * (case when story_has_flag(uid, 'learned_insurance_basics') then 0.03 else 0.04 end), 2);
  select cash_balance into v_cash from profiles where id = uid for update;
  if v_prem > v_cash then return jsonb_build_object('error', 'insufficient_cash', 'cash', v_cash, 'premium', v_prem); end if;
  v_days := story_game_months_to_days(12);          -- one game year in real days
  insert into venture_events (venture_id, kind, amount, description)
    values (v.id, 'expense', -v_prem, 'Insurance premium (theft and spoilage cover)');
  perform adjust_cash_balance(uid, -v_prem, 'venture_cost', 'ventures', v.id);
  update ventures set insured_until = now() + (v_days * interval '1 day') where id = v.id;
  return jsonb_build_object('ok', true, 'premium', v_prem);
end $$;

revoke all on function sim_collect_income() from public, anon;
grant execute on function sim_collect_income() to authenticated;
revoke all on function sim_venture_payout(bigint, numeric, numeric, numeric) from public, anon;
grant execute on function sim_venture_payout(bigint, numeric, numeric, numeric) to authenticated;
revoke all on function sim_buy_cover(bigint) from public, anon;
grant execute on function sim_buy_cover(bigint) to authenticated;
