-- FinLit Zambia — 07-venture-decisions.sql (safe to re-run)
-- Venture problems, opportunities and profit decisions, told from the mentor's side.
-- Amounts are shares of the venture's capital. Choice keys: cash_pct_capital, venture_mult{mult,days},
-- venture_guard_days, requires_insured, venture_note, retained_withdraw_pct, retained_reinvest_pct.

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_break_in$k$, $k$venture_event$k$, $k$venture_event$k$, $j${}$j$::jsonb, $j${}$j$::jsonb, $k$inner_voice$k$, $t$Break-in at {venture}$t$, $t${name} calls you early in the morning.$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t$Overnight, thieves broke into {venture} and took stock and cash worth about 15% of what {name} put in. {name} has to decide how to respond before opening, and asks what you think.$t$, $j$[{"label": "Advise {name} to replace everything straight away", "cash_pct_capital": -0.15, "venture_note": "Replaced all stolen stock", "sets_flag": "replaced_stolen_stock", "narrative": "{name} is back in business by lunchtime, but it was an expensive morning."}, {"label": "Advise {name} to restock only the fast sellers", "cash_pct_capital": -0.08, "venture_mult": {"mult": 0.8, "days": 4}, "venture_note": "Partial restock after theft", "sets_flag": "partial_restock_after_theft", "narrative": "Cheaper now, but with thin shelves {name} will lose some sales for the next few days."}, {"label": "Tell {name} to claim on the insurance", "requires_insured": true, "cash_pct_capital": -0.02, "reputation_delta": 1, "venture_note": "Insurance excess (claim paid the rest)", "sets_flag": "claimed_insurance", "narrative": "The cover pays the rest. This is exactly what the premium was for."}, {"label": "Advise {name} to fit a proper lock, hire a guard, and restock slowly", "cash_pct_capital": -0.09, "venture_guard_days": 14, "venture_mult": {"mult": 0.7, "days": 3}, "venture_note": "New lock and guard after theft", "sets_flag": "secured_premises", "narrative": "It costs now and slows sales for a few days, but a break-in is much less likely over the coming year."}, {"label": "Advise {name} to absorb the loss and carry on with what is left", "venture_mult": {"mult": 0.6, "days": 6}, "sets_flag": "absorbed_theft", "narrative": "No cash goes out today, but a half-empty stall sells a lot less, and {name} is exposed to it happening again."}]$j$::jsonb from story_events where event_key = $k$venture_break_in$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_equipment_breaks$k$, $k$venture_event$k$, $k$venture_event$k$, $j${}$j$::jsonb, $j${}$j$::jsonb, $k$inner_voice$k$, $t$Key equipment breaks at {venture}$t$, $t${name} sounds stressed on the phone.$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t$The equipment that {venture} depends on has broken down. Repairs are not covered by insurance. What do you advise {name}?$t$, $j$[{"label": "Advise {name} to patch it cheaply", "cash_pct_capital": -0.04, "venture_mult": {"mult": 0.85, "days": 6}, "venture_note": "Cheap patch repair", "sets_flag": "patched_equipment", "narrative": "It works again, mostly. Work is slower until {name} can afford a real fix."}, {"label": "Advise {name} to replace it properly", "cash_pct_capital": -0.1, "venture_note": "Replaced equipment", "sets_flag": "replaced_equipment", "narrative": "A bigger bill, but {name} will not think about it again for a long time."}, {"label": "Advise {name} to borrow equipment from a neighbour for now", "venture_mult": {"mult": 0.75, "days": 3}, "reputation_delta": 1, "sets_flag": "borrowed_equipment", "narrative": "It costs nothing, but {name} depends on a favour and works more slowly. They should return the kindness."}]$j$::jsonb from story_events where event_key = $k$venture_equipment_breaks$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_spoilage$k$, $k$venture_event$k$, $k$venture_event$k$, $j${}$j$::jsonb, $j${"venture_categories": ["retail", "agriculture"]}$j$::jsonb, $k$inner_voice$k$, $t$Stock spoiling at {venture}$t$, $t$A power cut and a heat wave hit at the same time.$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t${name}'s stock at {venture} is starting to spoil, and it could cost around 12% of their capital if nothing is done. What do you advise?$t$, $j$[{"label": "Advise {name} to sell it all cheap today", "cash_pct_capital": -0.06, "venture_note": "Cleared spoiling stock at a discount", "sets_flag": "sold_spoiling_stock", "narrative": "{name} recovers some of the value, and customers love the bargain."}, {"label": "Advise {name} to throw it away", "cash_pct_capital": -0.12, "venture_note": "Spoiled stock written off", "sets_flag": "wrote_off_spoiled_stock", "narrative": "A clean break, but the full loss lands on {name}."}, {"label": "Tell {name} to claim on the insurance", "requires_insured": true, "cash_pct_capital": -0.02, "reputation_delta": 1, "venture_note": "Insurance excess (claim paid the rest)", "sets_flag": "claimed_insurance", "narrative": "The cover pays out. {name} loses only the excess."}, {"label": "Advise {name} to pay for ice and a cool box to save most of it", "cash_pct_capital": -0.04, "venture_guard_days": 7, "venture_note": "Ice and cool box for stock", "sets_flag": "invested_in_cooling", "narrative": "{name} saves most of the stock, and the cool box will protect against spoilage for the next week too."}]$j$::jsonb from story_events where event_key = $k$venture_spoilage$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_slump$k$, $k$venture_event$k$, $k$venture_event$k$, $j${}$j$::jsonb, $j${}$j$::jsonb, $k$inner_voice$k$, $t$Customers staying away from {venture}$t$, $t${name} notices foot traffic dropping.$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t$A rival has opened nearby, and {venture} is seeing fewer customers than usual. {name} has a few days to react and asks for your advice.$t$, $j$[{"label": "Advise {name} to cut prices to keep customers coming", "venture_mult": {"mult": 0.85, "days": 6}, "sets_flag": "cut_prices", "narrative": "{name} keeps the customers but earns less on each sale, so profits stay lower for the week."}, {"label": "Advise {name} to spend on promotion (flyers, WhatsApp status, a sign)", "cash_pct_capital": -0.04, "venture_mult": {"mult": 1.1, "days": 6}, "venture_note": "Promotion spend", "sets_flag": "promoted_business", "narrative": "It costs upfront, but people notice. Sales hold up and edge above normal."}, {"label": "Advise {name} to hold prices and wait it out", "venture_mult": {"mult": 0.6, "days": 6}, "sets_flag": "held_prices_in_slump", "narrative": "{name} protects their margins but loses a lot of customers while waiting."}]$j$::jsonb from story_events where event_key = $k$venture_slump$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_big_order$k$, $k$venture_event$k$, $k$venture_event$k$, $j${}$j$::jsonb, $j${"venture_categories": ["retail", "services", "tech"]}$j$::jsonb, $k$inner_voice$k$, $t$A big order for {venture}$t$, $t$A customer wants a lot more than usual.$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t$A customer asks {name} for a big order from {venture}. {name} would need to spend about 8% of their capital upfront to fill it, and it pays back well when delivered. What do you advise?$t$, $j$[{"label": "Advise {name} to take the order", "cash_pct_capital": -0.08, "venture_note": "Stock and materials for the big order", "sets_flag": "took_big_order", "narrative": "{name} puts the money in and gets to work. Payment is due in a day or so."}, {"label": "Advise {name} to take it, but ask for a 50% deposit first", "requires_flag": "learned_breakeven_math", "cash_pct_capital": -0.04, "reputation_delta": 1, "venture_note": "Stock for the big order (after deposit)", "sets_flag": "took_big_order_with_deposit", "narrative": "The deposit covers half the costs, so {name} puts in less of their own cash and carries less risk."}, {"label": "Advise {name} to decline politely", "sets_flag": "declined_big_order", "narrative": "{name} keeps their cash safe and carries on as normal."}]$j$::jsonb from story_events where event_key = $k$venture_big_order$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_big_order_paid$k$, $k$consequence$k$, $k$flag_delay$k$, $j${"after_flag": "took_big_order", "delay_real_days": 1}$j$::jsonb, $j${}$j$::jsonb, $k$inner_voice$k$, $t$Big order delivered$t$, $t$$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t$The customer pays {name} for the big order for {venture}.$t$, $j$[{"label": "Collect the payment", "cash_pct_capital": 0.16, "venture_note": "Big order payment", "narrative": "Delivered and paid. Taking on the risk paid off this time."}]$j$::jsonb from story_events where event_key = $k$venture_big_order_paid$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_big_order_paid_deposit$k$, $k$consequence$k$, $k$flag_delay$k$, $j${"after_flag": "took_big_order_with_deposit", "delay_real_days": 1}$j$::jsonb, $j${}$j$::jsonb, $k$inner_voice$k$, $t$Big order delivered$t$, $t$$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t$The customer pays {name} the balance of the big order for {venture}.$t$, $j$[{"label": "Collect the payment", "cash_pct_capital": 0.16, "venture_note": "Big order balance", "narrative": "Delivered and paid. The deposit meant {name} risked far less of their own cash."}]$j$::jsonb from story_events where event_key = $k$venture_big_order_paid_deposit$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

insert into story_events (event_key, category, trigger_type, trigger_config, eligibility_config, character_key, title, intro, entry_node)
values ($k$venture_profit_decision$k$, $k$venture_payout$k$, $k$venture_payout$k$, $j${}$j$::jsonb, $j${}$j$::jsonb, $k$inner_voice$k$, $t$Profit at {venture}$t$, $t$The books are looking healthy.$t$, 'start')
on conflict (event_key) do update set category = excluded.category, trigger_type = excluded.trigger_type, trigger_config = excluded.trigger_config,
  eligibility_config = excluded.eligibility_config, character_key = excluded.character_key, title = excluded.title, intro = excluded.intro;
insert into story_nodes (event_id, node_key, body, choices)
select id, $k$start$k$, $t$About {retained} of profit has built up inside {venture}. It is not in {name}'s pocket yet. What do you advise {name} to do with it?$t$, $j$[{"label": "Advise {name} to take it all home", "retained_withdraw_pct": 1, "sets_flag": "withdrew_profits", "narrative": "{name} pays themselves in full. Cash goes up now, and the business keeps running on what it already has."}, {"label": "Advise {name} to reinvest it all in the business", "retained_reinvest_pct": 1, "sets_flag": "reinvested_profits", "narrative": "Every kwacha goes back in. The business grows, though with no cash in {name}'s pocket and returns that taper off as it gets bigger."}, {"label": "Advise {name} to split it: half home, half reinvested", "retained_withdraw_pct": 0.5, "retained_reinvest_pct": 0.5, "sets_flag": "split_profits", "narrative": "A balanced choice: {name} enjoys some of the reward while the business keeps growing."}, {"label": "Advise {name} to leave it in the business as a safety buffer", "sets_flag": "kept_profit_buffer", "narrative": "The profit stays put. If something goes wrong at {venture}, it will be paid from here first, before {name} touches their own cash."}]$j$::jsonb from story_events where event_key = $k$venture_profit_decision$k$
on conflict (event_id, node_key) do update set body = excluded.body, choices = excluded.choices;

