-- FinLit Zambia — Financial Character Simulator
-- 09-yungsta-questions.sql  (safe to re-run)  Run AFTER 08.
--
-- THE YUNGSTA ASKS QUESTIONS. Once a learner has finished a lesson, the yungsta they guide
-- occasionally asks a question about it ("Mwila asks: ..."), and the learner answers by telling
-- them what is right. This is retrieval practice plus learning-by-teaching:
--   * the questions are the lessons' OWN quiz questions (so they match what was taught),
--   * a wrong answer is corrected on the spot, and the same question comes back ~2 days later,
--   * at most 2 new questions per real day, at least 3 hours apart, so it never becomes a chore.

create table if not exists learner_lessons (        -- which lessons each learner has completed
  profile_id uuid not null references profiles(id) on delete cascade,
  lesson_id text not null,
  completed_at timestamptz not null default now(),
  primary key (profile_id, lesson_id)
);

create table if not exists yungsta_questions (
  id bigint generated always as identity primary key,
  question_key text not null unique,
  lesson_id text not null,
  topic text,
  question text not null,
  options jsonb not null,          -- [{"text": "...", "fb": "why this is right or wrong"}]
  correct_index int not null,
  is_active boolean not null default true
);

create table if not exists learner_questions (
  id bigint generated always as identity primary key,
  profile_id uuid not null references profiles(id) on delete cascade,
  question_id bigint not null references yungsta_questions(id),
  attempt int not null default 1,
  option_order int[] not null,     -- how this ask shuffles the options (display position -> original index)
  status text not null default 'pending',    -- pending | answered
  available_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  chosen_index int,                -- original option index
  correct boolean
);
create index if not exists learner_questions_lookup on learner_questions (profile_id, status, available_at);

alter table learner_lessons enable row level security;
alter table yungsta_questions enable row level security;
alter table learner_questions enable row level security;
drop policy if exists "own lessons (read)" on learner_lessons;
create policy "own lessons (read)" on learner_lessons for select using (auth.uid() = profile_id);
drop policy if exists "own questions (read)" on learner_questions;
create policy "own questions (read)" on learner_questions for select using (auth.uid() = profile_id);
-- the question bank (with the answers) is NOT readable by learners; only the functions below can read it
revoke all on yungsta_questions from anon, authenticated;
revoke insert, update, delete, truncate on learner_lessons, learner_questions from anon, authenticated;

-- ── pick and schedule the next question ──
create or replace function yungsta_schedule(p uuid)
returns void language plpgsql security definer set search_path = public as $$
declare q yungsta_questions; n int;
begin
  if exists (select 1 from learner_questions where profile_id = p and status = 'pending') then return; end if;
  if (select count(*) from learner_questions where profile_id = p and created_at::date = current_date) >= 2 then return; end if;
  if exists (select 1 from learner_questions where profile_id = p and created_at > now() - interval '3 hours') then return; end if;

  select yq.* into q from yungsta_questions yq
   where yq.is_active
     and exists (select 1 from learner_lessons ll where ll.profile_id = p and ll.lesson_id = yq.lesson_id)
     and not exists (select 1 from learner_questions lq where lq.profile_id = p and lq.question_id = yq.id
                      and (lq.status = 'pending' or lq.created_at > now() - interval '20 hours'))
   order by (select max(lq.created_at) from learner_questions lq where lq.profile_id = p and lq.question_id = yq.id) asc nulls first,
            random()
   limit 1;
  if q.id is null then return; end if;

  n := jsonb_array_length(q.options);
  insert into learner_questions (profile_id, question_id, option_order)
  values (p, q.id, array(select i from generate_series(0, n - 1) i order by random()));
end $$;

-- ── the question waiting for the learner (never includes the right answer) ──
create or replace function yungsta_current(p uuid)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare lq learner_questions; q yungsta_questions; v_opts jsonb;
begin
  select * into lq from learner_questions
   where profile_id = p and status = 'pending' and available_at <= now()
   order by available_at limit 1;
  if lq.id is null then return null; end if;
  select * into q from yungsta_questions where id = lq.question_id;
  select jsonb_agg(jsonb_build_object('index', ord - 1, 'text', story_fill(p, q.options -> (idx) ->> 'text')) order by ord)
    into v_opts from unnest(lq.option_order) with ordinality as t(idx, ord);
  return jsonb_build_object('id', lq.id, 'topic', q.topic, 'question', story_fill(p, q.question),
                            'options', v_opts, 'attempt', lq.attempt);
end $$;

-- ── the learner answers (index = the position shown on screen) ──
create or replace function yungsta_answer(p_id bigint, p_choice int)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid(); lq learner_questions; q yungsta_questions;
  v_orig int; v_ok boolean; v_n int;
begin
  if uid is null then return jsonb_build_object('error', 'not_signed_in'); end if;
  select * into lq from learner_questions
   where id = p_id and profile_id = uid and status = 'pending' and available_at <= now() for update;
  if not found then return jsonb_build_object('error', 'not_found'); end if;
  v_n := array_length(lq.option_order, 1);
  if p_choice is null or p_choice < 0 or p_choice >= v_n then return jsonb_build_object('error', 'bad_choice'); end if;
  select * into q from yungsta_questions where id = lq.question_id;

  v_orig := lq.option_order[p_choice + 1];
  v_ok := (v_orig = q.correct_index);
  update learner_questions set status = 'answered', answered_at = now(), chosen_index = v_orig, correct = v_ok where id = lq.id;

  perform yungsta_mark_guided(uid);
  if v_ok and lq.attempt = 1 then perform adjust_reputation_score(uid, 0.5, 'taught correctly: ' || q.question_key); end if;
  -- a wrong answer comes back in about 2 real days (up to 3 tries in all)
  if not v_ok and lq.attempt < 3 then
    insert into learner_questions (profile_id, question_id, attempt, option_order, available_at)
    values (uid, q.id, lq.attempt + 1,
            array(select i from generate_series(0, v_n - 1) i order by random()), now() + interval '2 days');
  end if;

  return jsonb_build_object(
    'correct', v_ok,
    'reaction', story_fill(uid, case when v_ok then '{name}: "Ohh, that makes sense! I will remember that."'
                                     else '{name}: "Hmm, okay. I will try it your way. Let''s check this one again soon."' end),
    'feedback', story_fill(uid, q.options -> v_orig ->> 'fb'),
    'right_text', story_fill(uid, q.options -> q.correct_index ->> 'text'),
    'explanation', story_fill(uid, q.options -> q.correct_index ->> 'fb'),
    'returns', (not v_ok and lq.attempt < 3));
end $$;

do $$
declare r record;
begin
  for r in select p.oid::regprocedure as sig, p.proname from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.proname in ('yungsta_schedule', 'yungsta_current', 'yungsta_answer')
  loop
    execute format('revoke all on function %s from public, anon', r.sig);
    if r.proname = 'yungsta_answer' then execute format('grant execute on function %s to authenticated', r.sig); end if;
  end loop;
end $$;

-- ── the question bank: the lessons' own quiz questions, reworded so the yungsta asks them in the first person ──
insert into yungsta_questions (question_key, lesson_id, topic, question, options, correct_index) values
($k$0a-q1$k$, $k$0a$k$, $t$Definition$t$, $t$What is financial literacy?$t$, $j$[{"text": "Having a bank account", "fb": "Literacy is about knowledge and confidence, not any single product."}, {"text": "The knowledge, skills, and confidence to make informed money decisions", "fb": "This is the exact definition used throughout this curriculum."}, {"text": "A way of earning more money", "fb": "Earning more is income. Literacy is about understanding and managing money well."}]$j$::jsonb, 1),
($k$0a-q2$k$, $k$0a$k$, $t$Capability vs Literacy$t$, $t$Is financial capability the same as financial literacy?$t$, $j$[{"text": "Yes, they're identical", "fb": "Capability also requires access to appropriate products and services."}, {"text": "No — capability requires access too, not just knowledge", "fb": "You can know what to do without having access to actually do it."}]$j$::jsonb, 1),
($k$0a-q3$k$, $k$0a$k$, $t$Informal Tools$t$, $t$Which of these is an informal financial tool used in Zambia?$t$, $j$[{"text": "Chilimba", "fb": "A rotating savings group with no regulatory protection."}, {"text": "NAPSA", "fb": "NAPSA is a formal, regulated statutory body."}, {"text": "A bank savings account", "fb": "That is a formal financial product, not an informal tool."}]$j$::jsonb, 0),
($k$0a-q5$k$, $k$0a$k$, $t$Household Resilience$t$, $t$How does financial literacy support household resilience?$t$, $j$[{"text": "It helps families absorb shocks without falling into crisis debt", "fb": "This is the key mechanism: knowledge and planning let families absorb shocks without falling into crisis debt."}, {"text": "It guarantees a family will never face financial hardship", "fb": "Literacy improves resilience, but doesn't eliminate risk entirely."}, {"text": "It makes everyone earn more", "fb": "Literacy improves decisions, but it does not by itself raise anyone's income."}]$j$::jsonb, 0),
($k$0b-q1$k$, $k$0b$k$, $t$Fee Comparison$t$, $t$Why does sending money cross-network usually cost more than same-network?$t$, $j$[{"text": "Higher provider charges apply for inter-network transfers", "fb": "Cross-network transfers carry meaningfully higher fees than sending within the same network."}, {"text": "They actually cost the same", "fb": "The fee comparison tool showed a real, significant difference."}]$j$::jsonb, 0),
($k$0b-q2$k$, $k$0b$k$, $t$Government Levy$t$, $t$Does switching providers let me avoid the Mobile Money Transaction Levy?$t$, $j$[{"text": "Yes, some providers don't charge it", "fb": "The levy is government-applied and unavoidable on sends, regardless of provider."}, {"text": "No — it applies regardless of provider", "fb": "The levy is built into every send transaction's total fee."}]$j$::jsonb, 1),
($k$0b-q3$k$, $k$0b$k$, $t$USSD Access$t$, $t$What does USSD access require that an app doesn't?$t$, $j$[{"text": "An internet connection", "fb": "USSD is exactly the method that doesn't need internet."}, {"text": "Nothing extra — it works on any phone, no internet needed", "fb": "This is exactly why USSD matters so much for rural and feature-phone access."}]$j$::jsonb, 1),
($k$0b-q4$k$, $k$0b$k$, $t$KYC$t$, $t$What does KYC stand for?$t$, $j$[{"text": "Keep Your Cash", "fb": "That's not the correct expansion."}, {"text": "Know Your Customer", "fb": "The standard identity verification requirement across financial services."}, {"text": "Know Your Charges", "fb": "KYC is about verifying who the customer is, not about fees."}]$j$::jsonb, 1),
($k$0b-q5$k$, $k$0b$k$, $t$Transaction Limits$t$, $t$Why do mobile money accounts have transaction limits?$t$, $j$[{"text": "To manage fraud and money-laundering risk based on verification level", "fb": "Tiered limits directly correspond to how thoroughly your identity has been verified."}, {"text": "To force people to use bank accounts instead", "fb": "The goal is risk management, not pushing people toward a specific product."}, {"text": "Because phones cannot handle large amounts", "fb": "Limits come from risk and verification rules, not from what phones can handle."}]$j$::jsonb, 0),
($k$0c-q1$k$, $k$0c$k$, $t$OTP Safety$t$, $t$Who should I ever share my OTP with?$t$, $j$[{"text": "Provider staff, if they ask", "fb": "Genuine staff will never ask for your OTP."}, {"text": "No one, ever", "fb": "An OTP should never be shared, under any circumstances."}, {"text": "Your bank manager, if they call you", "fb": "Genuine staff never need your OTP, however convincing they sound."}, {"text": "A family member you trust", "fb": "Even trusted people can be impersonated or tricked. Your OTP is for you alone."}]$j$::jsonb, 1),
($k$0c-q2$k$, $k$0c$k$, $t$SIM Swap Protection$t$, $t$What protects me specifically against SIM swap fraud?$t$, $j$[{"text": "A SIM port PIN set through your provider", "fb": "A port PIN stops fraudsters from transferring your number without your explicit authorisation."}, {"text": "Changing your mobile money PIN often", "fb": "This doesn't specifically prevent your number being ported to another SIM."}]$j$::jsonb, 0),
($k$0c-q4$k$, $k$0c$k$, $t$Right Regulator$t$, $t$Which regulator handles a dispute over an insurance claim?$t$, $j$[{"text": "Bank of Zambia", "fb": "BoZ handles banks and mobile money."}, {"text": "Pensions and Insurance Authority (PIA)", "fb": "PIA regulates insurance and pension products specifically."}, {"text": "Zambia Revenue Authority (ZRA)", "fb": "ZRA handles tax, not insurance claim disputes."}]$j$::jsonb, 1),
($k$0c-q5$k$, $k$0c$k$, $t$Recognising Scams$t$, $t$A message says my account will be suspended unless I click a link immediately. What is this?$t$, $j$[{"text": "A normal account update", "fb": "This is a classic phishing pattern."}, {"text": "Almost certainly a phishing attempt", "fb": "Manufactured urgency plus a link is a textbook scam pattern."}, {"text": "A prize you have won", "fb": "Prizes you never entered for are a classic lure."}]$j$::jsonb, 1),
($k$0d-q1$k$, $k$0d$k$, $t$Money Mindset$t$, $t$What is a "money script"?$t$, $j$[{"text": "A budgeting spreadsheet template", "fb": "That's not what a money script refers to."}, {"text": "An unconscious belief about money formed early in life", "fb": "Money scripts quietly shape spending and saving habits for years."}]$j$::jsonb, 1),
($k$0d-q5$k$, $k$0d$k$, $t$Rural Growth$t$, $t$What drove rural financial inclusion to grow faster than the national average since 2020?$t$, $j$[{"text": "New bank branches built in rural areas", "fb": "Bank branch expansion wasn't the main driver."}, {"text": "Mobile money agent networks reaching areas without bank branches", "fb": "Mobile money agents reach areas that bank branches do not."}]$j$::jsonb, 1),
($k$1-0-q1$k$, $k$1-0$k$, $t$Deductions$t$, $t$I earn K3,500 gross. NAPSA takes 5%. How much is my NAPSA deduction?$t$, $j$[{"text": "K150.00", "fb": "5% of K3,500 is K175.00."}, {"text": "K175.00", "fb": "K3,500 × 5% = K175.00."}, {"text": "K200.00", "fb": "5% of K3,500 is K175.00, not K200."}]$j$::jsonb, 1),
($k$1-0-q2$k$, $k$1-0$k$, $t$PAYE Threshold$t$, $t$Below what monthly taxable income does someone pay zero PAYE?$t$, $j$[{"text": "K5,100", "fb": "The first K5,100 of taxable income is tax-free."}, {"text": "K3,000", "fb": "The threshold is K5,100."}, {"text": "K7,100", "fb": "But that's actually the top of the 20% band, not the tax-free threshold."}]$j$::jsonb, 0),
($k$1-0-q3$k$, $k$1-0$k$, $t$50/30/20 Rule$t$, $t$Under the 50/30/20 rule, what percentage should go toward savings?$t$, $j$[{"text": "50%", "fb": "That's the Needs allocation, not savings."}, {"text": "30%", "fb": "That's the Wants allocation, not savings."}, {"text": "20%", "fb": "20% goes to savings under this guideline."}]$j$::jsonb, 2),
($k$1-0-q4$k$, $k$1-0$k$, $t$NAPSA and PAYE$t$, $t$Does my NAPSA contribution reduce how much PAYE I pay?$t$, $j$[{"text": "Yes — NAPSA is deducted first, lowering your taxable income", "fb": "This was true before 2018, but a change to the Income Tax Act means PAYE is now calculated directly on gross income, unaffected by NAPSA."}, {"text": "No — PAYE is calculated on gross income directly", "fb": "Since 1 January 2018, NAPSA no longer reduces the PAYE base. Both NAPSA and PAYE are calculated independently from your gross income (source: zra.org.zm)."}]$j$::jsonb, 1),
($k$1-0-q5$k$, $k$1-0$k$, $t$SMART Goals$t$, $t$What does the "M" in SMART goals stand for?$t$, $j$[{"text": "Money", "fb": "Think about how you'd track progress."}, {"text": "Measurable", "fb": "A good goal has a real number you can track."}, {"text": "Monthly", "fb": "The correct word is \"Measurable\"."}]$j$::jsonb, 1),
($k$1-1-q1$k$, $k$1-1$k$, $t$Compound Interest$t$, $t$What makes compound interest different from simple interest?$t$, $j$[{"text": "It has a higher rate", "fb": "The rate can be identical. The difference is what the interest is calculated on."}, {"text": "It's calculated on the growing balance, including past interest", "fb": "Compound interest earns interest on interest, which is why it accelerates over time."}, {"text": "It's only available at certain banks", "fb": "Compounding is a calculation method, not a bank-specific feature."}]$j$::jsonb, 1),
($k$1-1-q2$k$, $k$1-1$k$, $t$Deposit Protection$t$, $t$What protects my money if a licensed Zambian bank fails?$t$, $j$[{"text": "Nothing — you lose it all", "fb": "This is exactly why formal banking is safer than cash at home."}, {"text": "The Deposit Protection Fund Board", "fb": "Overseen by the Bank of Zambia, it protects eligible deposits up to a set limit."}, {"text": "Your employer", "fb": "This has nothing to do with your employer."}]$j$::jsonb, 1),
($k$1-1-q3$k$, $k$1-1$k$, $t$Mobile Money vs Bank$t$, $t$Does mobile money typically pay the same interest as a bank savings account?$t$, $j$[{"text": "No — mobile wallets are built for transactions, not growth", "fb": "Mobile money is excellent for transacting, but a savings account is designed for growth."}, {"text": "Yes, they're identical", "fb": "Mobile wallets typically pay little to no interest."}]$j$::jsonb, 0),
($k$1-1-q4$k$, $k$1-1$k$, $t$Chilimba Risk$t$, $t$What's the biggest risk of relying solely on a chilimba for savings?$t$, $j$[{"text": "It's too slow", "fb": "Speed isn't the main risk here."}, {"text": "Zero legal protection if the organiser disappears", "fb": "A chilimba can be a great savings discipline, but it has no legal safety net if something goes wrong."}, {"text": "It requires a smartphone", "fb": "Chilimba groups typically don't require any technology at all."}]$j$::jsonb, 1),
($k$1-1-q5$k$, $k$1-1$k$, $t$Consistency$t$, $t$Which builds wealth more reliably — small consistent monthly saving, or occasional large deposits?$t$, $j$[{"text": "Small consistent monthly saving", "fb": "Consistency builds the habit and benefits from more compounding periods."}, {"text": "Occasional large deposits", "fb": "Irregular saving is far more likely to get skipped entirely."}]$j$::jsonb, 0),
($k$1-2-q1$k$, $k$1-2$k$, $t$Loan Costs$t$, $t$Which typically has the highest interest rate in Zambia?$t$, $j$[{"text": "A formal bank loan", "fb": "Bank loans typically have the lowest rates of the three."}, {"text": "A microfinance loan", "fb": "Microfinance sits between bank loans and payday lenders."}, {"text": "A payday lender", "fb": "Payday lenders typically charge the highest rates, often 35% or more."}]$j$::jsonb, 2),
($k$1-2-q2$k$, $k$1-2$k$, $t$Avalanche Method$t$, $t$The avalanche method pays off which debt first?$t$, $j$[{"text": "The smallest balance", "fb": "That's the snowball method, not avalanche."}, {"text": "The highest interest rate", "fb": "Avalanche targets the highest rate first, minimising total interest paid."}, {"text": "The oldest debt", "fb": "Age of debt isn't the deciding factor in either method."}]$j$::jsonb, 1),
($k$1-2-q3$k$, $k$1-2$k$, $t$Co-Signing$t$, $t$If I co-sign a loan for a friend and they don't pay, what happens?$t$, $j$[{"text": "Nothing — it's not your responsibility", "fb": "Co-signing makes you equally liable for the debt."}, {"text": "You become responsible for the debt", "fb": "Co-signing makes you equally liable, even though you never received the money."}, {"text": "Only the bank is affected", "fb": "The lender can pursue the co-signer for the full debt."}]$j$::jsonb, 1),
($k$1-2-q4$k$, $k$1-2$k$, $t$On-Time Payment$t$, $t$What is generally the single strongest factor in creditworthiness?$t$, $j$[{"text": "How much you earn", "fb": "Income matters less than repayment behaviour."}, {"text": "Consistently paying on time", "fb": "On-time repayment is the strongest signal of reliability to any lender."}, {"text": "How many loans you've had", "fb": "Quantity of loans matters far less than repayment reliability."}]$j$::jsonb, 1),
($k$1-2-q5$k$, $k$1-2$k$, $t$Emergency Borrowing$t$, $t$What is the safest source of funds for a true emergency?$t$, $j$[{"text": "Your own emergency fund", "fb": "A pre-built emergency fund avoids interest entirely and any borrowing risk."}, {"text": "A payday lender", "fb": "Payday lenders are the most expensive option, best avoided if possible."}, {"text": "A loan app that approves in minutes", "fb": "Very fast approval usually means very high cost, so it is not the safest source."}]$j$::jsonb, 0),
($k$1-3-q1$k$, $k$1-3$k$, $t$Target Size$t$, $t$What is the common guideline for emergency fund size?$t$, $j$[{"text": "1 week of expenses", "fb": "This is too small to provide real protection against a genuine shock."}, {"text": "3 to 6 months of essential expenses", "fb": "This range balances real protection against a realistic savings timeline."}, {"text": "A full year's salary", "fb": "This target is far larger than the standard guideline and can feel discouraging to start."}]$j$::jsonb, 1),
($k$1-3-q2$k$, $k$1-3$k$, $t$Where to Keep It$t$, $t$Where should an emergency fund typically be kept?$t$, $j$[{"text": "Locked in a 5-year fixed deposit", "fb": "This defeats the purpose since you can't access it quickly in a real emergency."}, {"text": "Somewhere liquid, like a savings account or mobile money", "fb": "Accessibility is essential, since emergencies don't wait for a maturity date."}, {"text": "Invested in LuSE shares", "fb": "Share prices can fall exactly when you need the money most, which defeats the fund's purpose."}]$j$::jsonb, 1),
($k$1-3-q3$k$, $k$1-3$k$, $t$True Emergency$t$, $t$Which of these is a true emergency-fund-worthy expense?$t$, $j$[{"text": "A limited-time sale on something you want", "fb": "Manufactured urgency from a sale is not a genuine emergency."}, {"text": "Losing your only source of transport to work", "fb": "If it threatens your ability to earn income, it qualifies as a true emergency."}, {"text": "A new phone because mine is a bit old", "fb": "Wanting an upgrade is not an emergency."}]$j$::jsonb, 1),
($k$1-3-q4$k$, $k$1-3$k$, $t$Building the Fund$t$, $t$What's the most reliable way to build an emergency fund over time?$t$, $j$[{"text": "Wait for a lump sum, like a bonus", "fb": "Waiting for windfalls often means the fund never actually gets built."}, {"text": "A small automatic transfer every payday", "fb": "Automating removes the dependence on willpower and builds the fund steadily."}, {"text": "Save whatever is left at the end of the month", "fb": "Whatever is left is often nothing. Paying yourself first works better."}]$j$::jsonb, 1),
($k$1-3-q5$k$, $k$1-3$k$, $t$Starting Small$t$, $t$Is a 1-month starter fund still worth building, even if the full target is 6 months?$t$, $j$[{"text": "Yes — even a partial fund reduces vulnerability", "fb": "You don't need the full target to already be meaningfully protected."}, {"text": "No — only a complete fund provides any protection", "fb": "Partial protection is still real protection, and waiting for \"complete\" often means never starting."}]$j$::jsonb, 0),
($k$2-0-q2$k$, $k$2-0$k$, $t$Risk Management and Insurance$t$, $t$An asset is worth K20,000. The annual premium is K800. The probability of loss this year is 3%. What is the expected loss?$t$, $j$[{"text": "K800 — equal to the premium", "fb": "That's the premium, not the expected loss calculation."}, {"text": "K600 — K20,000 × 3%", "fb": "Expected loss = Asset Value × Probability = K20,000 × 0.03 = K600. Since this is below the K800 premium, the insurer is pricing in a margin — normal and expected."}, {"text": "K20,000 — the full asset value", "fb": "That would be the loss if it definitely happened — expected loss weights it by probability."}, {"text": "K3 — 3% alone", "fb": "The percentage must be applied to the asset value, not used alone."}]$j$::jsonb, 1),
($k$2-0-q3$k$, $k$2-0$k$, $t$Risk Management and Insurance$t$, $t$What is an insurance "excess"?$t$, $j$[{"text": "Extra optional coverage you can add", "fb": "That describes an add-on, not an excess."}, {"text": "The amount you pay yourself before the insurer covers the rest of a claim", "fb": "A K500 excess means the policyholder pays the first K500 of a claim themselves, and the insurer covers the rest."}, {"text": "A penalty for filing too many claims", "fb": "Excess applies to every claim, not as a penalty for frequency."}, {"text": "The total premium paid over the policy's life", "fb": "That describes cumulative premium cost, not excess."}]$j$::jsonb, 1),
($k$2-0-q4$k$, $k$2-0$k$, $t$Risk Management and Insurance$t$, $t$Which type of insurance is legally mandatory for every vehicle on Zambian roads?$t$, $j$[{"text": "Comprehensive cover", "fb": "Comprehensive is optional — it protects your own vehicle, not a legal requirement."}, {"text": "Third-party cover", "fb": "Every vehicle must carry at least third-party insurance — driving without it is illegal, separate from any financial risk."}, {"text": "Life insurance", "fb": "Life insurance has no connection to vehicle registration requirements."}, {"text": "None — insurance is always optional in Zambia", "fb": "Third-party motor cover is a genuine legal requirement."}]$j$::jsonb, 1),
($k$2-0-q5$k$, $k$2-0$k$, $t$Risk Management and Insurance$t$, $t$Where should I direct a dispute over a denied insurance claim in Zambia?$t$, $j$[{"text": "Bank of Zambia", "fb": "BoZ regulates banks and mobile money, not insurance."}, {"text": "Pensions and Insurance Authority (PIA)", "fb": "PIA regulates insurance and pensions specifically."}, {"text": "Securities and Exchange Commission", "fb": "SEC regulates investment schemes, not insurance disputes."}, {"text": "ZRA", "fb": "ZRA handles taxation, not insurance regulation."}]$j$::jsonb, 1),
($k$2-1-q2$k$, $k$2-1$k$, $t$Basics of Investing$t$, $t$I invest K5,000 in a 182-day T-Bill at a 14% annualised rate. Approximately how much gross interest do I earn over the 182 days (before tax)?$t$, $j$[{"text": "K700 — the full annual rate applied directly", "fb": "14% is an annualised rate — you must adjust it for the actual 182-day holding period."}, {"text": "~K349 — K5,000 × 14% × (182÷365)", "fb": "The annualised rate is scaled down to the actual number of days you hold the bill."}, {"text": "K5,700 — principal plus a flat 14%", "fb": "This treats the annual rate as if it applied to the full period, not adjusted for 182 days."}, {"text": "K0 — T-Bills only pay out at the 364-day tenor", "fb": "All four tenors pay interest at maturity, including 182-day bills."}]$j$::jsonb, 1),
($k$2-1-q3$k$, $k$2-1$k$, $t$Basics of Investing$t$, $t$What percentage withholding tax applies to T-Bill interest for a domestic individual investor?$t$, $j$[{"text": "0% — T-Bills are entirely tax-free", "fb": "A 15% withholding tax applies — T-Bills are not tax-free."}, {"text": "15%", "fb": "This is deducted from the interest earned, not the principal — always calculate your NET return."}, {"text": "30%", "fb": "30% is not the correct T-Bill withholding rate."}, {"text": "37% — same as the top PAYE band", "fb": "T-Bill withholding tax is a separate, lower rate from PAYE bands."}]$j$::jsonb, 1),
($k$2-1-q4$k$, $k$2-1$k$, $t$Basics of Investing$t$, $t$Why does diversification (spreading money across savings, T-Bills, and LuSE shares) reduce risk?$t$, $j$[{"text": "It guarantees higher total returns", "fb": "Diversification manages risk — it doesn't guarantee higher returns."}, {"text": "If one investment performs poorly, the others may offset the loss, reducing overall exposure to any single failure", "fb": "This is the core principle behind spreading risk across multiple asset types."}, {"text": "It eliminates all investment risk entirely", "fb": "No investment strategy eliminates risk completely."}, {"text": "It avoids the need for an emergency fund", "fb": "An emergency fund remains essential regardless of portfolio diversification."}]$j$::jsonb, 1),
($k$2-1-q5$k$, $k$2-1$k$, $t$Basics of Investing$t$, $t$Someone offers me an investment promising LuSE-level returns with savings-account-level safety and no risk of loss. What should I conclude?$t$, $j$[{"text": "This is a rare but genuine opportunity", "fb": "Risk and return move together — this combination doesn't exist legitimately."}, {"text": "This is almost certainly fraudulent — high return with no risk is not a real combination", "fb": "This is the same red flag as in crypto scams, and it applies to any investment claim."}, {"text": "It depends on which broker is offering it", "fb": "The mathematical impossibility of the claim doesn't change based on who's offering it."}, {"text": "This is only possible through a REIT", "fb": "REITs don't offer this risk-free high-return combination either."}]$j$::jsonb, 1),
($k$2-2-q3$k$, $k$2-2$k$, $t$Housing and Major Purchases$t$, $t$A car depreciates 15% per year. Why does this matter even if I never plan to sell it?$t$, $j$[{"text": "It doesn't matter — depreciation only matters when you sell", "fb": "Depreciation is a real ongoing cost to your net worth, regardless of your selling intentions."}, {"text": "It's a genuine annual cost — your net worth falls by that amount whether or not you sell", "fb": "Depreciation is often the single largest annual cost of owning a vehicle."}, {"text": "It only matters for insurance premiums", "fb": "Depreciation affects your overall net worth, not just insurance calculations."}, {"text": "It's cancelled out by fuel savings over time", "fb": "These are separate, unrelated costs — one doesn't offset the other."}]$j$::jsonb, 1),
($k$2-2-q5$k$, $k$2-2$k$, $t$Housing and Major Purchases$t$, $t$Why does the break-even point between renting and buying usually take several years to reach?$t$, $j$[{"text": "Rent always increases faster than mortgage payments", "fb": "This isn't the core reason for the delayed break-even point."}, {"text": "The large upfront buying costs (deposit, PTT, legal fees) take years of avoided rent to offset", "fb": "Buying starts with a big cost disadvantage that only closes gradually over time."}, {"text": "Mortgages always cost more in total than renting, permanently", "fb": "The whole point of a break-even calculation is that buying does eventually win."}, {"text": "It never actually happens in Zambia", "fb": "The calculator explicitly shows a real break-even year under reasonable assumptions."}]$j$::jsonb, 1),
($k$2-3-q1$k$, $k$2-3$k$, $t$Agricultural & Rural Finance$t$, $t$Under FISP 2025/26, roughly how much does a farmer contribute toward an input package worth around K8,400 in total?$t$, $j$[{"text": "K4,000 — half the total cost", "fb": "The farmer's share is far smaller than half."}, {"text": "K400 — a small fraction, with government covering the rest", "fb": "This is what makes FISP genuinely transformative for smallholder access to inputs."}, {"text": "Nothing — the programme is entirely free", "fb": "Farmers do contribute a portion, even if small."}, {"text": "K8,400 — the full cost", "fb": "That would defeat the purpose of a support programme."}]$j$::jsonb, 1),
($k$2-3-q2$k$, $k$2-3$k$, $t$Agricultural & Rural Finance$t$, $t$How does weather-index insurance differ from a typical insurance claims process?$t$, $j$[{"text": "It requires an inspector to visit every individual field", "fb": "This is the opposite of how index insurance works."}, {"text": "It pays out automatically once rainfall data crosses a set threshold — no individual claim needed", "fb": "The \"index\" is the rainfall measurement itself, not an individual assessment."}, {"text": "It only pays out if the farmer proves total crop loss", "fb": "There's no individual proof-of-loss requirement in index insurance."}, {"text": "It never actually pays out — it's a marketing concept only", "fb": "Real payouts occur when the rainfall threshold is triggered."}]$j$::jsonb, 1),
($k$2-3-q3$k$, $k$2-3$k$, $t$Agricultural & Rural Finance$t$, $t$Approximately what percentage of Zambia's 1.5 million smallholder farmers have access to any form of credit?$t$, $j$[{"text": "Around 75%", "fb": "Access is far lower than this — 75% is closer to the rural poverty rate, a different statistic."}, {"text": "Around 14%", "fb": "Roughly 14.2% of smallholders have access to any credit at all — a genuinely severe access gap."}, {"text": "Around 50%", "fb": "Actual access is significantly lower than half."}, {"text": "Nearly 100%", "fb": "Credit access is one of the most severe gaps in Zambian smallholder farming."}]$j$::jsonb, 1),
($k$2-3-q4$k$, $k$2-3$k$, $t$Agricultural & Rural Finance$t$, $t$Why do many Zambian smallholder farmers use informal lenders instead of formal loans like CEEC's 12% agricultural loan?$t$, $j$[{"text": "Informal loans are always genuinely cheaper", "fb": "Informal loans are reported as substantially more expensive, not cheaper."}, {"text": "Formal credit requires collateral, registration, and paperwork that many smallholders can't provide", "fb": "This is a genuine structural access barrier, not simply a preference."}, {"text": "Formal lenders refuse to lend to farmers under any circumstances", "fb": "Formal agricultural loans do exist and are used — just not accessible to everyone."}, {"text": "Informal lenders are required by law for agricultural loans", "fb": "No such legal requirement exists."}]$j$::jsonb, 1),
($k$2-3-q5$k$, $k$2-3$k$, $t$Agricultural & Rural Finance$t$, $t$What is the most realistic path for a smallholder farmer to eventually access lower-cost, formal credit?$t$, $j$[{"text": "Wait for the government to remove all collateral requirements", "fb": "This isn't a realistic near-term individual strategy."}, {"text": "Join a registered farmers' cooperative or union to build collective standing", "fb": "Cooperative membership is the practical route most often available to individual smallholders."}, {"text": "Only use informal lenders permanently", "fb": "This doesn't build toward eventually accessing lower-cost formal credit."}, {"text": "Avoid all forms of credit entirely", "fb": "Avoiding credit entirely isn't a realistic strategy for input-intensive farming."}]$j$::jsonb, 1),
($k$2-4-q2$k$, $k$2-4$k$, $t$Entrepreneurship & Small Business Finance$t$, $t$My fixed costs are K600/month. Each unit sells for K10 and costs K6 to produce. What is my break-even point?$t$, $j$[{"text": "60 units — K600 ÷ K10", "fb": "This divides by the full price, not the contribution margin (price minus variable cost)."}, {"text": "150 units — K600 ÷ (K10 − K6)", "fb": "Each unit contributes K4 toward fixed costs — K600 ÷ K4 = 150 units."}, {"text": "100 units — K600 ÷ K6", "fb": "This divides by the variable cost alone, not the contribution margin."}, {"text": "6 units", "fb": "This is far too low — check the formula again."}]$j$::jsonb, 1),
($k$2-4-q3$k$, $k$2-4$k$, $t$Entrepreneurship & Small Business Finance$t$, $t$What is an "owner's draw"?$t$, $j$[{"text": "An informal, undocumented cash grab from the till", "fb": "This describes exactly what an owner's draw should NOT be."}, {"text": "A deliberate, recorded transfer of money from the business to personal use", "fb": "The key word is \"deliberate and recorded\" — not informal."}, {"text": "A type of business loan", "fb": "This isn't a loan product — it's an internal bookkeeping practice."}, {"text": "A tax paid by the business owner", "fb": "Not a tax — it's how an owner formally takes money out of their own business."}]$j$::jsonb, 1),
($k$2-4-q4$k$, $k$2-4$k$, $t$Entrepreneurship & Small Business Finance$t$, $t$What does CEEC typically require as security for a business loan?$t$, $j$[{"text": "Nothing — loans are unsecured", "fb": "CEEC loans typically require security, most commonly land-based collateral."}, {"text": "Land-based collateral, or a third-party guarantee", "fb": "This is a genuine access barrier for many new entrepreneurs, similar to formal agricultural credit."}, {"text": "A university degree", "fb": "Education level isn't a stated CEEC requirement."}, {"text": "A minimum of 10 years in business", "fb": "CEEC specifically prioritises youth and newer entrepreneurs, not long-established businesses only."}]$j$::jsonb, 1),
($k$2-4-q5$k$, $k$2-4$k$, $t$Entrepreneurship & Small Business Finance$t$, $t$What is chilimba?$t$, $j$[{"text": "A government business grant programme", "fb": "Chilimba is informal, not a government programme."}, {"text": "An informal rotating savings circle, widely used to raise small business capital", "fb": "It requires no formal collateral, making it genuinely accessible."}, {"text": "A type of business insurance", "fb": "Chilimba is a savings/lending arrangement, not insurance."}, {"text": "A CEEC loan product", "fb": "Chilimba is informal and community-based, separate from CEEC's formal lending."}]$j$::jsonb, 1),
($k$3-0-q1$k$, $k$3-0$k$, $t$Deduction Order$t$, $t$What is the correct deduction order on a Zambian payslip?$t$, $j$[{"text": "Gross → NAPSA deducted → PAYE on the remainder → NHIMA → Net Pay", "fb": "This was correct before 1 January 2018. Since then, an Income Tax Act amendment means NAPSA no longer reduces the PAYE base."}, {"text": "Gross → PAYE applied directly to gross → NAPSA and NHIMA deducted separately → Net Pay", "fb": "Since 1 January 2018, PAYE is calculated directly on gross income. NAPSA and NHIMA are both independent deductions that don't affect the PAYE calculation (source: zra.org.zm)."}, {"text": "Gross → NHIMA → NAPSA → PAYE on the remainder → Net Pay", "fb": "Neither NHIMA nor NAPSA reduce the PAYE base — PAYE is calculated on gross income directly, independent of both."}, {"text": "NAPSA is calculated on net pay, after everything else", "fb": "NAPSA is 5% of gross, calculated independently — not based on net pay."}]$j$::jsonb, 1),
($k$3-0-q2$k$, $k$3-0$k$, $t$Band Calculation$t$, $t$Gross salary K8,000. PAYE is calculated directly on gross. What is total PAYE?$t$, $j$[{"text": "K1,600 — 20% of the full K8,000", "fb": "20% applies only to the K2,000 slice between K5,101–K7,100. Not to the full K8,000."}, {"text": "K670 — Band 2: K2,000 × 20% = K400 · Band 3: K900 × 30% = K270", "fb": "Band 1 (K0–K5,100) = K0. Band 2 (K5,101–K7,100) = K2,000 × 20% = K400. Band 3: K8,000−K7,100 = K900 × 30% = K270. Total K670. Effective rate 8.4%."}, {"text": "K550 — using K7,600 (gross minus NAPSA) as the base", "fb": "This is the pre-2018 method. PAYE now applies to the full K8,000 gross, not K7,600."}, {"text": "K0 — below the K8,000 threshold", "fb": "The tax-free threshold is K5,100 — K8,000 exceeds this, so PAYE applies."}]$j$::jsonb, 1),
($k$3-0-q3$k$, $k$3-0$k$, $t$NAPSA Ceiling$t$, $t$What is the 2025 NAPSA ceiling and maximum monthly employee contribution?$t$, $j$[{"text": "No ceiling — always exactly 5% of any salary", "fb": "NAPSA has a ceiling of K34,164/month. Above this, contributions are capped at K1,708.20."}, {"text": "Ceiling: K34,164/month · Maximum contribution: K1,708.20", "fb": "Anyone earning above K34,164/month contributes only K1,708.20 — 5% of the ceiling, not 5% of their full salary."}, {"text": "Ceiling: K20,000 · Maximum: K1,000", "fb": "2025 ceiling is K34,164/month. Maximum contribution is K1,708.20."}, {"text": "Ceiling: K50,000 · Maximum: K2,500", "fb": "The verified 2025 figures are ceiling K34,164, maximum K1,708.20."}]$j$::jsonb, 1),
($k$3-0-q4$k$, $k$3-0$k$, $t$NHIMA Basis$t$, $t$NHIMA is calculated on which salary component — and does it affect the PAYE calculation?$t$, $j$[{"text": "Gross salary — and it reduces the PAYE base", "fb": "Both wrong. NHIMA is on basic salary only (not gross), and does NOT affect the PAYE calculation."}, {"text": "Net pay — and it reduces the PAYE base", "fb": "NHIMA is 1% of basic salary, calculated independently — it plays no role in the PAYE calculation at all."}, {"text": "Basic salary only — calculated entirely independently of PAYE, same as NAPSA", "fb": "NHIMA = 1% of basic salary. Excludes allowances and overtime. Like NAPSA, it has no effect on the PAYE calculation — both are calculated independently from gross income."}, {"text": "Net pay after all other deductions", "fb": "NHIMA is on basic salary — not on net pay."}]$j$::jsonb, 2),
($k$3-0-q5$k$, $k$3-0$k$, $t$Effective Rate$t$, $t$At K12,000 gross, effective PAYE is 17.2%. Which statement is most accurate?$t$, $j$[{"text": "You are in the 37% bracket and pay 37% of your salary in tax", "fb": "The 37% rate applies only to the slice above K9,200. Effective rate is 17.2% — not 37%."}, {"text": "K8,000 and K12,000 earners pay the same effective rate", "fb": "Progressive taxation means different effective rates. K8,000: 8.4%. K12,000: 17.2%."}, {"text": "Effective rate is 17.2% — K2,066 of K12,000 goes to PAYE. The 37% applies only to the K2,800 slice above K9,200.", "fb": "Effective rate = K2,066 ÷ K12,000 = 17.2%. The 37% band applies only to the top K2,800 slice (K1,036 of PAYE) — not the whole salary."}, {"text": "Net pay = K12,000 minus 17.2% = K9,936", "fb": "17.2% is PAYE only. Full deductions = NAPSA K600 + PAYE K2,066 + NHIMA K120 = K2,786. Net = K9,214."}]$j$::jsonb, 2),
($k$3-1-q1$k$, $k$3-1$k$, $t$Gambler's Fallacy$t$, $t$After losing 5 bets in a row on independent, random events, is a win "due"?$t$, $j$[{"text": "Yes — probability evens out over time", "fb": "Not for independent events. Each bet has the exact same odds regardless of what happened before."}, {"text": "No — each independent event has the same odds regardless of past results", "fb": "This is the Gambler's Fallacy. Independent random events have no memory of previous outcomes."}]$j$::jsonb, 1),
($k$3-1-q2$k$, $k$3-1$k$, $t$Loss Aversion$t$, $t$According to Kahneman & Tversky's research, how much more painful do losses feel compared to equivalent gains?$t$, $j$[{"text": "About the same", "fb": "Losses are felt significantly more strongly than equivalent gains."}, {"text": "Roughly 2.5 times more painful", "fb": "This asymmetry is why people hold falling investments far too long."}, {"text": "About 10 times more painful", "fb": "Research suggests roughly two to two and a half times, not ten."}]$j$::jsonb, 1),
($k$3-1-q3$k$, $k$3-1$k$, $t$Sunk Cost Fallacy$t$, $t$I've already spent K3,000 renovating a shop that isn't profitable. Should that K3,000 affect my decision to continue?$t$, $j$[{"text": "Yes — you should recover that investment first", "fb": "This is the Sunk Cost Fallacy. Past spending has no bearing on whether continuing makes sense now."}, {"text": "No — only future costs and returns should matter", "fb": "The K3,000 is gone either way. Only the decision going forward matters."}]$j$::jsonb, 1),
($k$3-1-q4$k$, $k$3-1$k$, $t$Systems vs Willpower$t$, $t$What is the most reliable way to defeat a cognitive bias like present bias?$t$, $j$[{"text": "Try harder to resist temptation in the moment", "fb": "Willpower in the moment is unreliable — the bias is strongest exactly when you're deciding."}, {"text": "Build a system that removes the decision before the moment arrives", "fb": "Pre-commitment (like an automatic savings transfer) defeats the bias structurally, not through willpower."}]$j$::jsonb, 1),
($k$3-1-q5$k$, $k$3-1$k$, $t$Mental Accounting$t$, $t$I spend a K1,000 bonus more freely than K1,000 of my salary. What is this called?$t$, $j$[{"text": "Social Proof", "fb": "Social Proof is about following others' financial decisions — not this."}, {"text": "Mental Accounting", "fb": "Treating money differently based on its source, even though a kwacha is a kwacha regardless of origin."}, {"text": "Present Bias", "fb": "Present bias is preferring rewards now over later. This is about treating money differently depending on where it came from."}]$j$::jsonb, 1),
($k$3-2-q1$k$, $k$3-2$k$, $t$SIM Swap Prevention$t$, $t$What single step most effectively prevents SIM swap fraud?$t$, $j$[{"text": "Setting a SIM port PIN with your network provider", "fb": "A SIM port PIN means any SIM replacement requires a code only you know."}, {"text": "Using a different mobile money provider", "fb": "SIM swap affects all networks. Switching providers doesn't prevent the attack."}, {"text": "Never using mobile money at all", "fb": "This avoids the attack at the cost of financial access entirely. The port PIN protects without giving up the service."}, {"text": "Keeping a larger emergency fund in cash", "fb": "An emergency fund helps recovery, not prevention."}]$j$::jsonb, 0),
($k$3-2-q2$k$, $k$3-2$k$, $t$Wrong Transfer Scam$t$, $t$I receive K800 from an unknown number. A message follows: "Wrong number, please send it back." What should I do?$t$, $j$[{"text": "Send it back immediately", "fb": "The original deposit is likely fake and will reverse. You'd be sending your own money."}, {"text": "Verify the deposit is real through the official app first, then use the network's official reversal process", "fb": "Never act on a caller's request alone — verify through official channels first."}, {"text": "Send half back as a compromise", "fb": "Any amount sent back is lost if the original deposit was fraudulent."}, {"text": "Block the number and spend the money", "fb": "The deposit may still reverse, leaving you with a negative balance."}]$j$::jsonb, 1),
($k$3-2-q3$k$, $k$3-2$k$, $t$Domain Checking$t$, $t$A message links to "zanaco-bank.com." What's wrong with this?$t$, $j$[{"text": "Nothing — it sounds legitimate", "fb": "This is a fraudulent domain. ZANACO's real domain is zanaco.co.zm."}, {"text": "The domain uses .com instead of the official .co.zm", "fb": "Legitimate Zambian institutions use .co.zm or .zm domains — never .com."}, {"text": "It should have arrived by email instead", "fb": "The delivery channel isn't the issue — the fraudulent domain is."}, {"text": "Accounts can't be suspended without a phone call", "fb": "Accounts can be suspended for real reasons — the issue here is specifically the fake domain."}]$j$::jsonb, 1),
($k$3-2-q4$k$, $k$3-2$k$, $t$Impersonation$t$, $t$A caller claims to be from MTN and asks for my OTP to "stop fraud." What do I do?$t$, $j$[{"text": "Give it quickly — every second counts", "fb": "No legitimate institution ever asks for your OTP. This urgency is manufactured."}, {"text": "Hang up. Call MTN's official number (100) yourself", "fb": "Hanging up breaks the fraudster's control of the situation."}, {"text": "Give only the first 3 digits", "fb": "Partial OTPs can still be exploited. Never share any part of it."}, {"text": "Ask them to call back later", "fb": "This still keeps you engaged with the fraudster — hang up immediately instead."}]$j$::jsonb, 1),
($k$3-2-q5$k$, $k$3-2$k$, $t$Connecting to Module 3.1$t$, $t$Which cognitive bias does the Fake Prize scam ("Act now!") most directly exploit?$t$, $j$[{"text": "Loss Aversion", "fb": "Involved somewhat, but present bias plus manufactured urgency is the primary driver."}, {"text": "Present Bias — manufactured urgency prevents careful thinking", "fb": "This is why smart people who know about scams still fall for them in the moment."}, {"text": "Sunk Cost Fallacy", "fb": "Sunk cost involves prior investment — this scam exploits urgency at the very start."}, {"text": "Gambler's Fallacy", "fb": "Gambler's Fallacy is about predicting random outcomes — not fabricated rewards."}]$j$::jsonb, 1),
($k$3-3-q1$k$, $k$3-3$k$, $t$Consumer Protection$t$, $t$What law replaced the 2017 Banking and Financial Services Act and the Money-lenders Act?$t$, $j$[{"text": "The Consumer Protection and Competition Act", "fb": "That's a separate, pre-existing act — not the one that replaced these two."}, {"text": "The Banking and Financial Services Act, 2026", "fb": "This consolidated and modernised financial regulation under expanded Bank of Zambia oversight."}, {"text": "The Citizens Economic Empowerment Act", "fb": "That is the CEEC's founding act and is unrelated to this reform."}, {"text": "No law has changed since 2017", "fb": "The 2026 Act is a genuine, significant legislative change."}]$j$::jsonb, 1),
($k$3-3-q2$k$, $k$3-3$k$, $t$Consumer Protection$t$, $t$Under the 2026 Act, what must an institution do before introducing or raising a consumer charge?$t$, $j$[{"text": "Nothing — fees can be changed at any time", "fb": "This is exactly what the Act now prohibits."}, {"text": "Get approval from the Bank of Zambia first", "fb": "An unapproved new or increased fee is a direct violation."}, {"text": "Publish it in a national newspaper", "fb": "Not the actual requirement — BoZ approval is."}, {"text": "Notify the SEC", "fb": "SEC regulates investments, not general banking fees — BoZ is the correct regulator here."}]$j$::jsonb, 1),
($k$3-3-q3$k$, $k$3-3$k$, $t$Consumer Protection$t$, $t$Which lenders now require a licence under the 2026 Act's single-window regime?$t$, $j$[{"text": "Only large commercial banks", "fb": "The licensing requirement is far broader than just large banks."}, {"text": "Banks, microfinance institutions, and digital lenders alike", "fb": "This closes a real gap — digital lending apps could not simply operate unlicensed."}, {"text": "Only foreign-owned lenders", "fb": "Ownership isn't the deciding factor — the type of financial activity is."}, {"text": "No lenders require a licence", "fb": "Universal licensing is a central feature of the 2026 Act."}]$j$::jsonb, 1),
($k$3-3-q4$k$, $k$3-3$k$, $t$Consumer Protection$t$, $t$Does Zambia currently have a dedicated financial services ombudsman?$t$, $j$[{"text": "Yes, since 2017", "fb": "No ombudsman exists yet — this is factually incorrect."}, {"text": "Not yet — it's under consideration, not yet established", "fb": "The sector regulator (BoZ, PIA, or SEC) is the real current escalation point instead."}, {"text": "Yes, run by ZICTA", "fb": "ZICTA regulates telecoms, not financial services complaints."}, {"text": "Yes, but only for insurance complaints", "fb": "No ombudsman exists for any financial sector yet."}]$j$::jsonb, 1),
($k$3-3-q5$k$, $k$3-3$k$, $t$Consumer Protection$t$, $t$Why does documenting a complaint in writing matter more in Zambia's current system?$t$, $j$[{"text": "It's a legal requirement to complain in writing", "fb": "Not a strict legal requirement — but a genuinely practical one."}, {"text": "Enforcement capacity is limited (as few as 5 national officers) — clear documentation gives your complaint the best chance", "fb": "Being realistic about a stretched system makes documentation more important, not less."}, {"text": "Verbal complaints are automatically ignored", "fb": "Not automatically ignored — just genuinely harder to act on with limited capacity."}, {"text": "It guarantees a fast resolution", "fb": "Nothing in the current system guarantees speed — courts especially can take years."}]$j$::jsonb, 1),
($k$3-4-q1$k$, $k$3-4$k$, $t$Remittances & Diaspora Finance$t$, $t$What two things combine to make up a remittance's "total cost"?$t$, $j$[{"text": "Only the advertised transfer fee", "fb": "The fee is only half the picture."}, {"text": "The transfer fee and the exchange rate margin", "fb": "The exchange rate margin is often larger than the fee itself, and far less visible."}, {"text": "Only how long the transfer takes", "fb": "Speed matters separately, but isn't part of the cost calculation itself."}, {"text": "A fixed government tax rate", "fb": "There's no fixed government remittance tax — cost varies entirely by provider."}]$j$::jsonb, 1),
($k$3-4-q3$k$, $k$3-4$k$, $t$Remittances & Diaspora Finance$t$, $t$What is the G20's target for global average remittance costs by 2027?$t$, $j$[{"text": "0% — remittances should be entirely free", "fb": "The actual target isn't zero — it's a specific reduced percentage."}, {"text": "3%", "fb": "Well below Sub-Saharan Africa's current regional average of around 7.9%."}, {"text": "15%", "fb": "15% is close to the current bank-transfer average — far above the actual target."}, {"text": "There is no global target", "fb": "The G20 has set an explicit 3% target for 2027."}]$j$::jsonb, 1),
($k$3-4-q4$k$, $k$3-4$k$, $t$Remittances & Diaspora Finance$t$, $t$Why might a slightly more expensive remittance provider still be the better choice?$t$, $j$[{"text": "Cost is the only factor that ever matters", "fb": "Cost matters a lot, but it is not the only factor: speed, pickup method and reliability matter too."}, {"text": "Speed, pickup method, and reliability can matter as much as total cost", "fb": "A recipient without a bank account, for example, needs a cash or mobile wallet pickup option regardless of fee."}, {"text": "More expensive providers are always more secure", "fb": "Price and security aren't directly correlated this way."}, {"text": "It's illegal to use the cheapest option", "fb": "No such restriction exists — this isn't a real consideration."}]$j$::jsonb, 1),
($k$3-4-q5$k$, $k$3-4$k$, $t$Remittances & Diaspora Finance$t$, $t$Where can I check real, current remittance costs for a specific corridor before sending money?$t$, $j$[{"text": "There's no way to check in advance", "fb": "A free tool exists specifically for this purpose."}, {"text": "remittanceprices.worldbank.org", "fb": "Free, real-time, and covers corridors worldwide including South Africa–Zambia."}, {"text": "Only by asking the provider directly, with no independent source", "fb": "An independent comparison tool exists — no need to rely on a single provider's own claims."}, {"text": "Bank of Zambia's website only", "fb": "Not the source to rely on here: the World Bank's dedicated tool is the independent reference."}]$j$::jsonb, 1),
($k$4-0-q1$k$, $k$4-0$k$, $t$Retirement Gap$t$, $t$A retired person's NAPSA pension is K1,800/month, and their monthly expenses are K3,200/month. What is their monthly retirement gap?$t$, $j$[{"text": "K800", "fb": "K3,200 − K1,800 = K1,400."}, {"text": "K1,200", "fb": "K3,200 − K1,800 = K1,400."}, {"text": "K1,400", "fb": "K3,200 expenses − K1,800 NAPSA = K1,400 per month shortage. This is why private savings matter — NAPSA alone is rarely enough."}, {"text": "K3,200", "fb": "K3,200 is her total expenses, not the gap."}]$j$::jsonb, 2),
($k$4-0-q2$k$, $k$4-0$k$, $t$The 3 Stages$t$, $t$Which retirement stage should a 19-year-old focus on?$t$, $j$[{"text": "Distribution — drawing income from savings", "fb": "Distribution is Stage 3 — retirement itself. At 19 you have decades before this stage."}, {"text": "Preservation — reducing investment risk", "fb": "Preservation is Stage 2 — for people approaching retirement around age 50–60."}, {"text": "Accumulation — saving and investing aggressively", "fb": "At 19 you are firmly in Stage 1 — Accumulation. This is the most powerful time to start because compound interest has the most years to work."}, {"text": "None — it is too early to think about retirement", "fb": "This is exactly the thinking that leaves people with no retirement savings."}]$j$::jsonb, 2),
($k$4-0-q3$k$, $k$4-0$k$, $t$Intestate Succession$t$, $t$What Zambian law governs who receives my assets if I die without a will?$t$, $j$[{"text": "The NAPSA Act", "fb": "The NAPSA Act governs pension contributions and benefits."}, {"text": "The Intestate Succession Act (Cap. 59)", "fb": "Cap. 59 sets fixed percentages for spouse, children, and parents — regardless of your wishes. A will overrides this entirely."}, {"text": "The Companies Act", "fb": "The Companies Act governs business registration — not personal estate distribution."}, {"text": "The Income Tax Act", "fb": "The Income Tax Act governs taxation — not asset distribution after death."}]$j$::jsonb, 1),
($k$4-0-q4$k$, $k$4-0$k$, $t$Time vs Amount$t$, $t$Person A saves K300/month from age 22 to 62 at 7% annual return. Person B saves K700/month from age 42 to 62 at 7%. Who retires with more money?$t$, $j$[{"text": "Person B — they save more per month", "fb": "More per month does not overcome fewer years of compounding."}, {"text": "Person A — more years of compounding outweighs the smaller monthly amount", "fb": "Person A builds ≈K913,000. Person B builds ≈K428,000. Starting 20 years earlier with less than half the monthly amount produces more than double the wealth. Time beats amount."}, {"text": "They produce the same result", "fb": "Compound interest makes time disproportionately powerful."}, {"text": "It depends on the bank", "fb": "At the same return rate, mathematics determines the outcome — not the bank."}]$j$::jsonb, 1),
($k$4-0-q5$k$, $k$4-0$k$, $t$Beneficiary Designation$t$, $t$What is the fastest way to ensure someone receives my NAPSA funds after I die, bypassing court entirely?$t$, $j$[{"text": "Write a detailed will", "fb": "A will still goes through court (probate). There is a faster route specifically for NAPSA funds."}, {"text": "Tell your family verbally who should receive your NAPSA", "fb": "Verbal instructions have no legal standing for NAPSA funds."}, {"text": "Name a beneficiary directly on your NAPSA account", "fb": "A named beneficiary receives NAPSA funds directly — no court, no probate, no delays. Update yours at enapsa.napsa.co.zm or dial *677#."}, {"text": "Register your family members with PACRA", "fb": "PACRA is for business registration — it has no role in NAPSA benefit distribution."}]$j$::jsonb, 2),
($k$4-1-q1$k$, $k$4-1$k$, $t$Phase 3 — PAYE$t$, $t$I earn K8,000 gross/month. PAYE is applied directly to gross (2025 bands: 0% to K5,100 · 20% to K7,100 · 30% to K9,200 · 37% above). What is my PAYE?$t$, $j$[{"text": "K0 — below the K5,100 threshold", "fb": "K8,000 is above the K5,100 threshold. Multiple bands apply above that point."}, {"text": "K670 — K400 at 20% + K270 at 30%", "fb": "Band 2 (K5,100.01–K7,100 = K2,000): K2,000 × 20% = K400. Band 3 (K7,100.01–K8,000 = K900): K900 × 30% = K270. Total PAYE: K670. Effective rate: K670 ÷ K8,000 = 8.4%."}, {"text": "K550 — using K7,600 (gross minus NAPSA) as the base", "fb": "This was correct before 1 January 2018. Since then, PAYE applies directly to the full K8,000 gross — not a reduced figure."}, {"text": "K1,520 — 20% of K7,600", "fb": "20% applies only to the K2,000 slice between K5,101–K7,100 — not to the full amount."}]$j$::jsonb, 1),
($k$4-1-q2$k$, $k$4-1$k$, $t$Phase 2 — Compound Interest$t$, $t$I save K200/month in a money market fund at 12% annual return for 5 years. Approximately how much will I have?$t$, $j$[{"text": "K12,000 — total deposits only", "fb": "K12,000 is what you deposited. The 12% annual return grows the fund above your deposits."}, {"text": "K10,000 — returns offset some deposits", "fb": "A 12% annual return increases your balance — it never reduces it."}, {"text": "Approximately K16,350", "fb": "At 12% annual (1% monthly) for 60 months: approximately K16,350. You deposited K12,000 — compound interest added approximately K4,350."}, {"text": "K24,000 — 12% × K12,000 × 2", "fb": "Compound interest doesn't work by simple multiplication — returns earn their own returns each month."}]$j$::jsonb, 2),
($k$4-1-q3$k$, $k$4-1$k$, $t$Phase 3 — Behavioural Economics$t$, $t$Which cognitive bias causes people to continue investing in a failing business because they have "already put in so much money"?$t$, $j$[{"text": "Sunk Cost Fallacy — past costs are irrelevant to future decisions", "fb": "The money already invested is gone regardless of your next decision. Only future costs and returns are relevant."}, {"text": "Loss Aversion — they hate realising the loss", "fb": "Loss aversion is about feeling losses more strongly than gains — not specifically about past investment driving future decisions."}, {"text": "Present Bias — the future feels less real", "fb": "Present bias is about preferring immediate rewards over future ones."}, {"text": "Gambler's Fallacy — they expect the business to turn around", "fb": "Gambler's Fallacy applies to random independent events — not to past-investment-driven reasoning."}]$j$::jsonb, 0),
($k$4-1-q4$k$, $k$4-1$k$, $t$Phase 4 — Estate Planning$t$, $t$What is the fastest way to protect my NAPSA funds so a named person receives them after my death, without court delays?$t$, $j$[{"text": "Write a will naming the recipient", "fb": "A will must go through probate — which takes time and involves court."}, {"text": "Tell your family verbally who should receive it", "fb": "Verbal instructions have no legal standing for NAPSA funds."}, {"text": "Name a beneficiary on your NAPSA account via enapsa.napsa.co.zm or *677#", "fb": "A named beneficiary receives funds directly — no court, no probate, no delays. Takes under 5 minutes."}, {"text": "Register your family with PACRA", "fb": "PACRA is for business registration — no role in NAPSA benefit distribution."}]$j$::jsonb, 2),
($k$4-1-q5$k$, $k$4-1$k$, $t$Phase 3 — Digital Security$t$, $t$I receive an SMS: "Your ZRA account has been flagged. Click here to verify: zra-zambia-secure.com." What do I do?$t$, $j$[{"text": "Click the link and enter your TPIN to verify", "fb": "This is a phishing attack. \"zra-zambia-secure.com\" is not a legitimate ZRA domain."}, {"text": "Call the number in the SMS to confirm the alert", "fb": "The number is controlled by the scammer — calling confirms your number is active."}, {"text": "Reply to the SMS asking for more details", "fb": "Replying confirms your number is active. Never engage with suspicious SMS messages."}, {"text": "Ignore the SMS and go directly to zra.org.zm by typing it yourself", "fb": "Official ZRA communications come from zra.org.zm. Never click links from SMS or WhatsApp — always type the address directly."}]$j$::jsonb, 3),
($k$4-2-q2$k$, $k$4-2$k$, $t$Health & Long-Term Care Planning$t$, $t$Where can NHIMA benefits actually be accessed?$t$, $j$[{"text": "Any hospital or clinic in Zambia", "fb": "Only accredited facilities qualify — not every provider does."}, {"text": "Only NHIMA-accredited facilities (with a genuine emergency exception)", "fb": "This is a real, practical limitation worth knowing before you need care urgently."}, {"text": "Only outside Zambia", "fb": "NHIMA is a domestic Zambian scheme — this isn't accurate."}, {"text": "Only at NHIMA's head office", "fb": "Benefits are accessed at accredited healthcare facilities, not an administrative office."}]$j$::jsonb, 1),
($k$4-2-q3$k$, $k$4-2$k$, $t$Health & Long-Term Care Planning$t$, $t$Why is buying health or critical illness cover early so much more important than, say, starting to invest early?$t$, $j$[{"text": "It isn't — both work the same way", "fb": "These two decisions work very differently, so they do not behave the same way."}, {"text": "Starting late on insurance can close the option entirely, not just reduce the benefit", "fb": "A late investment start costs growth; a late insurance start can mean no meaningful coverage at all."}, {"text": "Insurance is always cheaper when bought later", "fb": "The opposite is generally true — and availability itself can disappear, not just the price change."}, {"text": "NHIMA makes private cover unnecessary at any age", "fb": "NHIMA's real limits (covered in Section 1) are exactly why private cover still matters."}]$j$::jsonb, 1),
($k$4-2-q4$k$, $k$4-2$k$, $t$Health & Long-Term Care Planning$t$, $t$What is the dominant model of long-term care for older people in Zambia?$t$, $j$[{"text": "Government-run nursing homes", "fb": "Formal institutional care is comparatively rare in Zambia."}, {"text": "Family-based, home care", "fb": "This means realistic long-term care planning is often about being ready to support family directly."}, {"text": "Private international care facilities", "fb": "Not the dominant or accessible model for most Zambian families."}, {"text": "No care model exists", "fb": "Family-based care is a real, functioning (if under-resourced) system."}]$j$::jsonb, 1),
($k$4-2-q5$k$, $k$4-2$k$, $t$Health & Long-Term Care Planning$t$, $t$Who receives a guaranteed pension income in old age under Zambia's current system?$t$, $j$[{"text": "Every Zambian citizen automatically, universal pension", "fb": "No universal old-age pension currently exists in Zambia."}, {"text": "Only those with a formal NAPSA contribution history", "fb": "Anyone in informal work needs to plan deliberately for their own old-age income — there's no automatic safety net otherwise."}, {"text": "Only government employees", "fb": "NAPSA covers any formally employed contributor, not exclusively government workers."}, {"text": "Nobody — NAPSA does not exist", "fb": "NAPSA is real and functioning. It is just not universal to everyone."}]$j$::jsonb, 1),
($k$4-3-q1$k$, $k$4-3$k$, $t$Succession Law and Wills$t$, $t$Under the Intestate Succession Act, when a spouse and children survive, what does the surviving spouse receive?$t$, $j$[{"text": "Nothing", "fb": "This is exactly the property-grabbing misconception the Act does not support."}, {"text": "20% of the estate, plus a life interest in the matrimonial home", "fb": "A specific, legally guaranteed share — not everything, and not nothing."}, {"text": "100% — the entire estate", "fb": "This is only the case where no children survive alongside the spouse."}, {"text": "50%, equal to the children's combined share", "fb": "The spouse's share is 20%, distinct from the children's 50%."}]$j$::jsonb, 1),
($k$4-3-q2$k$, $k$4-3$k$, $t$Succession Law and Wills$t$, $t$What percentage do children receive when a spouse also survives?$t$, $j$[{"text": "20%", "fb": "20% is the spouse's share — children receive a different percentage."}, {"text": "50%, according to their ages and educational needs", "fb": "This is the largest single share under this distribution scenario."}, {"text": "0% — children never inherit directly", "fb": "Children have a real, substantial legal share under the Act."}, {"text": "100%", "fb": "100% would only apply if no spouse survives at all."}]$j$::jsonb, 1),
($k$4-3-q3$k$, $k$4-3$k$, $t$Succession Law and Wills$t$, $t$What does "letters of administration" actually grant?$t$, $j$[{"text": "Automatic ownership of the deceased's property to whoever applies first", "fb": "It's a formal court grant, not a first-come-first-served process."}, {"text": "Formal legal authority to manage and distribute the estate", "fb": "This authority does not exist informally — it requires a court application."}, {"text": "A tax exemption on the estate", "fb": "Not a tax mechanism — a legal authority-granting process."}, {"text": "Permission to write a will after someone has already died", "fb": "A will must be made before death — this isn't what letters of administration do."}]$j$::jsonb, 1),
($k$4-3-q4$k$, $k$4-3$k$, $t$Succession Law and Wills$t$, $t$Is property grabbing by relatives after a death legal in Zambia?$t$, $j$[{"text": "Yes, if the relatives are the deceased's parents or siblings", "fb": "The Act's specific distribution rules apply regardless of who is claiming property."}, {"text": "No — it is not supported by the Intestate Succession Act, despite remaining a real, documented practice", "fb": "Customary practice and the actual law can differ, and the law protects the surviving family."}, {"text": "Yes, in all cases without a will", "fb": "The Act's distribution rules apply specifically to prevent this, whether or not there's a will."}, {"text": "Only illegal if reported within 24 hours", "fb": "No such time limit exists — it's not legally permitted regardless of timing."}]$j$::jsonb, 1),
($k$4-3-q5$k$, $k$4-3$k$, $t$Succession Law and Wills$t$, $t$If the total estate value doesn't exceed K30,000, what happens?$t$, $j$[{"text": "The estate is forfeited to the state", "fb": "Small estates aren't forfeited — they follow a simplified process instead."}, {"text": "It devolves directly to the surviving spouse or children (or parents, if none) through a simplified process", "fb": "This avoids unnecessary court complexity for genuinely small estates."}, {"text": "The same full court process applies regardless of size", "fb": "The Act specifically simplifies the process for estates under this threshold."}, {"text": "It must be donated to charity", "fb": "No such requirement exists under the Act."}]$j$::jsonb, 1),
($k$b1-q2$k$, $k$b1$k$, $t$Starting & Running a Business$t$, $t$Within how many days of hiring my first employee must I register for NAPSA?$t$, $j$[{"text": "7 days", "fb": "The actual deadline is longer than this."}, {"text": "30 days", "fb": "NHIMA registration is required alongside it, on the same timeline."}, {"text": "90 days", "fb": "90 days is too long — the actual requirement is stricter."}, {"text": "There is no deadline", "fb": "A real, enforced deadline exists — 30 days from the first hire."}]$j$::jsonb, 1),
($k$b1-q3$k$, $k$b1$k$, $t$Starting & Running a Business$t$, $t$What is the key difference between a sole proprietorship and a limited company regarding liability?$t$, $j$[{"text": "There is no difference — liability works identically", "fb": "This is exactly the difference that matters most between these two structures."}, {"text": "A sole proprietor has unlimited personal liability; a company's liability is limited to its own assets", "fb": "As a sole proprietor, your personal savings and property are at risk if the business can't pay its debts."}, {"text": "Companies always have unlimited liability, sole proprietors never do", "fb": "This is the reverse of how it actually works."}, {"text": "Liability only applies to partnerships", "fb": "Liability considerations apply across all three structures, just differently."}]$j$::jsonb, 1),
($k$b1-q4$k$, $k$b1$k$, $t$Starting & Running a Business$t$, $t$In the bakery scenario, why couldn't the business get its local council trading permit without registering first?$t$, $j$[{"text": "Councils don't issue permits to bakeries", "fb": "The industry type wasn't the issue — the missing registration was."}, {"text": "Councils require proof of PACRA registration before issuing a trading permit", "fb": "This is why registration often has to come first, even for a small, local business."}, {"text": "The bakery needed a company structure specifically", "fb": "Any registered structure — including sole proprietorship — satisfies this requirement."}, {"text": "Home-based businesses can never get permits", "fb": "Home-based businesses can be permitted — registration is simply required first."}]$j$::jsonb, 1),
($k$b1-q5$k$, $k$b1$k$, $t$Starting & Running a Business$t$, $t$Why do serious investors typically require a company structure rather than a sole proprietorship before investing?$t$, $j$[{"text": "Sole proprietorships are illegal in Zambia", "fb": "Sole proprietorships are entirely legal — just not typically what investors will fund."}, {"text": "A company structure, clean registration, and compliance history are preconditions for due diligence", "fb": "For the app startup scenario, this wasn't optional — it was the literal precondition for raising capital."}, {"text": "Investors prefer higher registration fees", "fb": "The fee itself isn't the point — the legal and financial structure it creates is."}, {"text": "There's no real difference to investors", "fb": "This is a genuine, practical precondition, not a minor preference."}]$j$::jsonb, 1),
($k$b2-q1$k$, $k$b2$k$, $t$VAT — Input, Output & Compliance$t$, $t$A VAT-registered catering business charges a client K11,600 (K10,000 + 16% VAT). Whose money is the K1,600?$t$, $j$[{"text": "The business — income earned for services rendered", "fb": "This is a common mistake. The VAT was never the business's money."}, {"text": "ZRA — collected on the government's behalf and must be remitted", "fb": "Held temporarily, then remitted by the 18th of the following month after deducting input VAT."}, {"text": "The customer — they paid it so they own it", "fb": "The customer bears the economic cost, but once paid, it belongs to ZRA via the business."}, {"text": "Shared — 50% business, 50% ZRA", "fb": "No split exists — 100% of output VAT collected belongs to ZRA."}]$j$::jsonb, 1),
($k$b2-q2$k$, $k$b2$k$, $t$VAT — Input, Output & Compliance$t$, $t$A business has output VAT of K4,800 and input VAT of K1,920 this month. How much does it remit to ZRA?$t$, $j$[{"text": "K4,800 — the full output VAT", "fb": "The business can deduct input VAT paid — remitting the full amount means overpaying."}, {"text": "K1,920 — the input VAT only", "fb": "Input VAT is deducted from output VAT, not remitted on its own."}, {"text": "K2,880 — output VAT minus input VAT", "fb": "K4,800 − K1,920 = K2,880 — the net amount after recovering what was paid on purchases."}, {"text": "K6,720 — output plus input VAT", "fb": "Adding the two has no basis in VAT law — the formula is always subtraction."}]$j$::jsonb, 2),
($k$b2-q3$k$, $k$b2$k$, $t$VAT — Input, Output & Compliance$t$, $t$What is the critical difference between a zero-rated supply and an exempt supply?$t$, $j$[{"text": "No difference — both mean no VAT charged to the customer", "fb": "True for the customer, but completely different for the business — input VAT recovery is the key difference."}, {"text": "Zero-rated means 0% VAT; exempt means 8% VAT", "fb": "There is no 8% rate in Zambia's VAT system."}, {"text": "Zero-rated businesses can claim input VAT back; exempt businesses cannot", "fb": "An exporter (zero-rated) recovers all input VAT, often getting refunds. A school (exempt) absorbs input VAT as a cost."}, {"text": "Exempt businesses must register for VAT; zero-rated ones don't", "fb": "This is backwards — exempt-only businesses may not even need to register."}]$j$::jsonb, 2),
($k$b2-q4$k$, $k$b2$k$, $t$VAT — Input, Output & Compliance$t$, $t$At what annual turnover threshold is VAT registration mandatory, and by when must I register?$t$, $j$[{"text": "K5 million · within 30 days", "fb": "K5 million is the Corporate Income Tax threshold, not VAT's."}, {"text": "K1 million · within 14 days", "fb": "Neither figure is correct for VAT specifically."}, {"text": "K800,000 · within 30 days of exceeding it", "fb": "Failure to register is a criminal offence under the VAT Act — ZRA can back-date registration and assess VAT plus penalties."}, {"text": "K800,000 · within 14 days", "fb": "The threshold is right, but the deadline is 30 days. 14 days is WCFCB's deadline, not VAT's."}]$j$::jsonb, 2),
($k$b2-q5$k$, $k$b2$k$, $t$VAT — Input, Output & Compliance$t$, $t$From January 2025, what's required before a VAT-registered business can claim input VAT on a purchase?$t$, $j$[{"text": "A handwritten receipt from the supplier", "fb": "Handwritten receipts no longer qualify as valid VAT invoices."}, {"text": "A bank statement showing payment was made", "fb": "Proves payment, but isn't a VAT invoice."}, {"text": "A Smart Invoice receipt from ZRA's mandatory electronic system", "fb": "Without a Smart Invoice receipt, the VAT paid cannot be recovered."}, {"text": "Nothing — input VAT is automatic", "fb": "Not automatic — must be substantiated with valid documentation."}]$j$::jsonb, 2),
($k$b2-q6$k$, $k$b2$k$, $t$VAT — Input, Output & Compliance$t$, $t$An exporter pays 16% VAT on K5,000 (excl. VAT) of packaging but charges 0% on export sales. What is its VAT position?$t$, $j$[{"text": "Owes nothing, claims nothing — exports are exempt", "fb": "Exports are zero-rated, not exempt — this distinction changes everything."}, {"text": "Owes ZRA 16% on export sales", "fb": "Exports are zero-rated — 0% is charged on export sales themselves."}, {"text": "A K800 refund claim — output VAT K0, input VAT K800", "fb": "K0 − K800 = −K800 refund due. This is why exporters frequently receive VAT refunds — a deliberate policy incentive."}, {"text": "Must charge 16% on exports and cannot claim input VAT", "fb": "Exports are always zero-rated with full input VAT recovery — the opposite of this."}]$j$::jsonb, 2),
($k$u1-q1$k$, $k$u1$k$, $t$Property Transfer Tax$t$, $t$What is the correct Property Transfer Tax rate in Zambia from 1 January 2025?$t$, $j$[{"text": "5% — for developed properties", "fb": "5% was the previous rate. It's now 8% for all transfers."}, {"text": "8% of realised value — for all land and property transfers", "fb": "Effective 1 January 2025, PTT is standardised at 8% for all transfers — vacant or developed."}, {"text": "10% — raised in the 2025 Budget", "fb": "The correct rate is 8%, not 10%."}, {"text": "3% — the standard rate for all property", "fb": "3% is far below the current rate."}]$j$::jsonb, 1),
($k$u1-q2$k$, $k$u1$k$, $t$REIZ Entry Point$t$, $t$What is the minimum needed to invest in Zambia's commercial real estate through REIZ?$t$, $j$[{"text": "At least K200,000", "fb": "That's the cost of direct property, not REIZ shares."}, {"text": "A few hundred kwacha — one share through a LuSE-registered broker", "fb": "REIZ is publicly traded — any investor with a brokerage account can buy in."}, {"text": "USD 10,000 — institutional investors only", "fb": "No institutional minimum applies to REIZ."}, {"text": "K50,000 — LuSE minimum board lot", "fb": "No such REIT-specific minimum exists."}]$j$::jsonb, 1),
($k$u1-q3$k$, $k$u1$k$, $t$Land Title$t$, $t$Almost all land in Zambia is held under what type of title?$t$, $j$[{"text": "Freehold — outright ownership", "fb": "True freehold is rare in Zambia today."}, {"text": "99-year leasehold from the state", "fb": "Buyers hold a 99-year leasehold — the underlying land remains state property."}, {"text": "Customary title", "fb": "Customary land exists mainly in rural areas under traditional authorities."}, {"text": "Freehold converted to customary", "fb": "Freehold was converted to leasehold, not customary."}]$j$::jsonb, 1),
($k$u1-q4$k$, $k$u1$k$, $t$REIT Distribution Rule$t$, $t$REIZ must distribute what minimum percentage of distributable income annually?$t$, $j$[{"text": "50%", "fb": "The minimum is 75%, not 50%."}, {"text": "100%", "fb": "The requirement is a minimum of 75%, not 100%."}, {"text": "At least 75%", "fb": "This structural requirement is what makes REITs attractive income investments."}, {"text": "25%", "fb": "Dividends aren't optional for REITs — 75% is the required minimum."}]$j$::jsonb, 2),
($k$u1-q5$k$, $k$u1$k$, $t$Yield Calculation$t$, $t$A property valued at K650,000 rents for K5,500/month. What is the gross annual rental yield?$t$, $j$[{"text": "5.5%", "fb": "You need to annualise the rent first: K5,500 × 12 = K66,000."}, {"text": "10.2% — (K5,500 × 12) ÷ K650,000 × 100", "fb": "Annual rent K66,000 ÷ K650,000 × 100 = 10.2% gross yield."}, {"text": "8.5% — after deducting the 8% PTT", "fb": "PTT is a one-time acquisition cost, not deducted from annual yield."}, {"text": "6–8% — standard prime Lusaka band", "fb": "That's the prime residential band. Makeni/Silverest yields higher — 10%+."}]$j$::jsonb, 1),
($k$u2-q1$k$, $k$u2$k$, $t$Investment Analysis Fundamentals$t$, $t$A company's share price is K8.50 and its EPS is K0.85. What is the P/E ratio?$t$, $j$[{"text": "0.1 — EPS divided by share price", "fb": "That formula is inverted. P/E = Share Price ÷ EPS."}, {"text": "10 — K8.50 ÷ K0.85", "fb": "Investors are paying K10 for every K1 of annual earnings — reasonable for a stable LuSE company."}, {"text": "7.65 — price minus EPS", "fb": "P/E is a ratio, not a subtraction."}, {"text": "Cannot be calculated without the dividend", "fb": "P/E needs only share price and EPS."}]$j$::jsonb, 1),
($k$u2-q2$k$, $k$u2$k$, $t$Investment Analysis Fundamentals$t$, $t$DCZ generated ZMW 528.9M revenue and ZMW 3.48M net profit in 2024. What is the net profit margin?$t$, $j$[{"text": "15.2% — a healthy technology margin", "fb": "3.48 ÷ 528.9 × 100 = 0.66%, not 15.2%."}, {"text": "0.66% — ZMW 3.48M ÷ ZMW 528.9M × 100", "fb": "This razor-thin margin on massive revenue is typical of a growth-phase tech company."}, {"text": "66% — nearly two-thirds of revenue is profit", "fb": "That would make DCZ one of the most profitable companies in Africa. The decimal matters."}, {"text": "6.6% — a moderate margin for a new listing", "fb": "Check the decimal placement carefully when dividing millions."}]$j$::jsonb, 1),
($k$u2-q3$k$, $k$u2$k$, $t$Investment Analysis Fundamentals$t$, $t$A LuSE stock has a P/E of 4 — much lower than similar companies at 12–15. What does this most likely indicate?$t$, $j$[{"text": "An automatic buy signal — the stock is definitely undervalued", "fb": "Low P/E is not automatic. Investigate why first."}, {"text": "Either undervalued relative to peers, or the market expects earnings to decline — investigation required", "fb": "Read the annual report and SENS announcements before concluding it's a bargain."}, {"text": "The company pays no dividends", "fb": "Dividend payment is unrelated to P/E ratio."}, {"text": "The company's revenue is declining", "fb": "P/E uses earnings, not revenue."}]$j$::jsonb, 1),
($k$u2-q4$k$, $k$u2$k$, $t$Investment Analysis Fundamentals$t$, $t$A company's dividend yield is 12%. What should a careful investor check first?$t$, $j$[{"text": "Nothing — 12% yield is always a strong buy", "fb": "A 12% yield can be a trap: it may signal a falling share price or a payout the company cannot sustain."}, {"text": "Whether the share price has recently fallen sharply, and whether the dividend is sustainable", "fb": "Check: is revenue/profit supporting the dividend? Has the price dropped? Is the payout ratio below 80%?"}, {"text": "The company's P/E ratio — dividends and P/E must align", "fb": "No such rule exists. They measure different things."}, {"text": "The company's market cap — small caps should not pay high dividends", "fb": "Market cap doesn't determine dividend policy."}]$j$::jsonb, 1),
($k$u2-q5$k$, $k$u2$k$, $t$Investment Analysis Fundamentals$t$, $t$Where would I find the official dividend declaration for a LuSE company the moment it is announced?$t$, $j$[{"text": "The company's own website", "fb": "Not the official channel. SENS on luse.co.zm is required."}, {"text": "African-markets.com", "fb": "Excellent aggregator, but it aggregates secondary data."}, {"text": "SENS on luse.co.zm — the mandatory official announcement channel", "fb": "All dividend declarations, earnings, and rights issues must be published through SENS first."}, {"text": "The annual report — dividends are only declared once a year", "fb": "Some companies declare interim and final dividends — announced via SENS immediately."}]$j$::jsonb, 2),
($k$u3-q1$k$, $k$u3$k$, $t$Free-Float Requirements$t$, $t$What is the minimum public free-float required for LuSE Alt-M vs the main board?$t$, $j$[{"text": "25% for both markets", "fb": "The main board requires 25%. Alt-M has a lower threshold."}, {"text": "10% for Alt-M, 25% for the main board", "fb": "Alt-M's lower threshold makes listing accessible to growth-stage companies."}, {"text": "5% for Alt-M", "fb": "5% doesn't appear in LuSE listing requirements. The Alt-M minimum is 10%."}, {"text": "50% for all new listings", "fb": "No company would give up majority control on listing."}]$j$::jsonb, 1),
($k$u3-q2$k$, $k$u3$k$, $t$Direct Listing vs IPO$t$, $t$What is the key difference between a direct listing and a traditional IPO?$t$, $j$[{"text": "Direct listings are only available on the Alt-M", "fb": "Klapton Re's direct listing was on the main board."}, {"text": "In a direct listing, no new shares are issued and no capital is raised", "fb": "Existing shares are simply listed for trading — no subscription, no dilution."}, {"text": "A direct listing requires a sponsoring broker; an IPO does not", "fb": "This is the opposite — IPOs require a sponsoring broker."}, {"text": "A direct listing skips SEC approval", "fb": "SEC approval is required regardless."}]$j$::jsonb, 1),
($k$u3-q3$k$, $k$u3$k$, $t$The 50-Shareholder Rule$t$, $t$At what shareholder threshold must a company register its shares with the SEC?$t$, $j$[{"text": "100 shareholders", "fb": "The threshold is 50, not 100."}, {"text": "50 shareholders", "fb": "This catches many fast-growing SMEs by surprise."}, {"text": "200 shareholders", "fb": "Not a relevant threshold in Zambian securities law."}, {"text": "There is no threshold", "fb": "Registration is mandatory at 50+ shareholders."}]$j$::jsonb, 1),
($k$u3-q4$k$, $k$u3$k$, $t$Capital Gains Tax$t$, $t$I buy ZMW 20,000 of shares and sell 3 years later for ZMW 45,000. How much capital gains tax on the ZMW 25,000 profit?$t$, $j$[{"text": "ZMW 8,750 at 35%", "fb": "No capital gains tax applies to LuSE share transactions."}, {"text": "ZMW 3,750 at 15%", "fb": "There's no 15% capital gains tax on LuSE shares."}, {"text": "Zero — no capital gains tax on LuSE share transactions", "fb": "The full ZMW 25,000 is yours — compare to an 8% PTT on property."}, {"text": "ZMW 2,000 — PTT applies", "fb": "PTT applies only to land and property, not shares."}]$j$::jsonb, 2),
($k$u3-q5$k$, $k$u3$k$, $t$Oversubscription$t$, $t$DCZ's IPO was 114% oversubscribed. If I applied for 500 shares, approximately how many would I receive?$t$, $j$[{"text": "500 — first applicants are guaranteed", "fb": "IPO allocations in an oversubscribed offer aren't first-come-first-served."}, {"text": "Zero — oversubscribed IPOs reject retail applicants", "fb": "50% of the DCZ offer was reserved for retail investors."}, {"text": "Approximately 234 shares — scaled back proportionally (500 ÷ 2.14)", "fb": "Apply for more than you want when you expect oversubscription."}, {"text": "1,000 — extra shares are issued to meet demand", "fb": "The total offer size is fixed — it can't be expanded."}]$j$::jsonb, 2),
($k$u4-q1$k$, $k$u4$k$, $t$Cryptocurrency Fundamentals$t$, $t$Someone on WhatsApp offers to "invest" my money and promises to double it in 48 hours. What should I do?$t$, $j$[{"text": "Send a small amount to test it first", "fb": "This is a classic \"small win first\" fraud technique — testing doesn't protect you."}, {"text": "Ask which exchange they use and verify it", "fb": "Any answer they give is fabricated. The guarantee itself is proof of fraud."}, {"text": "Do not send any money — guaranteed returns in crypto do not exist", "fb": "Even Bitcoin regularly loses 30–50% of its value. Any guarantee is fraud. Block and report."}, {"text": "Ask to see their account history as proof", "fb": "Screenshots are trivially easy to fake. Proof of profit proves nothing."}]$j$::jsonb, 2),
($k$u4-q2$k$, $k$u4$k$, $t$Cryptocurrency Fundamentals$t$, $t$What is the maximum number of Bitcoin that will ever exist?$t$, $j$[{"text": "Unlimited — mined indefinitely", "fb": "Bitcoin has a hard cap of 21 million written into its code."}, {"text": "21 million — a hard cap that can never be changed", "fb": "Approximately 19.7 million have been mined as at 2025. This enforced scarcity underlies Bitcoin's \"digital gold\" argument."}, {"text": "1 billion", "fb": "The cap is 21 million — Bitcoin was designed to be scarce."}, {"text": "The Bank of Zambia controls the supply", "fb": "No central bank or government controls Bitcoin's supply — it's determined by code."}]$j$::jsonb, 1),
($k$u4-q3$k$, $k$u4$k$, $t$Cryptocurrency Fundamentals$t$, $t$I want to hold USD-equivalent savings without Bitcoin's volatility. Which type of crypto is designed for this?$t$, $j$[{"text": "Meme coins", "fb": "Meme coins are among the most volatile assets in crypto — the opposite of stable."}, {"text": "Ethereum", "fb": "Ethereum regularly moves 15–25% in a week — not designed as a stable store of value."}, {"text": "Stablecoins — USDT and USDC are pegged 1:1 to the US dollar", "fb": "Stablecoins give you crypto's speed with the dollar's stability — effectively holding USD without a US bank account."}, {"text": "Small market cap altcoins", "fb": "The opposite is true — small caps are the most volatile and easily manipulated."}]$j$::jsonb, 2),
($k$u4-q4$k$, $k$u4$k$, $t$Cryptocurrency Fundamentals$t$, $t$What does "not your keys, not your coins" mean in practice?$t$, $j$[{"text": "You must print your key on paper", "fb": "Paper wallets exist, but that's not the core meaning of the phrase."}, {"text": "If your crypto is on an exchange, the exchange controls the private keys — and if it's hacked or collapses, your funds may be lost", "fb": "FTX (2022) lost billions of customer funds this exact way. Self-custody wallets are safer for significant holdings."}, {"text": "Share your key with a trusted friend as backup", "fb": "Never share your private key with anyone, under any circumstances."}, {"text": "Exchanges are always safer due to security teams", "fb": "Exchanges are high-value hacker targets precisely because they hold many users' funds."}]$j$::jsonb, 1),
($k$u4-q5$k$, $k$u4$k$, $t$Cryptocurrency Fundamentals$t$, $t$What is Dollar Cost Averaging (DCA) and why is it recommended for beginners?$t$, $j$[{"text": "Buying in USD rather than kwacha", "fb": "DCA is about timing, not which currency you use."}, {"text": "Selling immediately when price rises 10%", "fb": "That's active price-target trading — not DCA."}, {"text": "Investing a fixed amount at regular intervals regardless of price", "fb": "When prices are high you buy less; when low, you buy more — your average smooths out over time."}, {"text": "Diversifying across 20+ altcoins", "fb": "Spreading across many altcoins increases exposure to scams, not reduces it."}]$j$::jsonb, 2)
on conflict (question_key) do update set lesson_id = excluded.lesson_id, topic = excluded.topic, question = excluded.question,
  options = excluded.options, correct_index = excluded.correct_index, is_active = true;

-- retire any earlier version of a question that was removed in the polish pass
update yungsta_questions set is_active = false where question_key not in ($k$0a-q1$k$,$k$0a-q2$k$,$k$0a-q3$k$,$k$0a-q5$k$,$k$0b-q1$k$,$k$0b-q2$k$,$k$0b-q3$k$,$k$0b-q4$k$,$k$0b-q5$k$,$k$0c-q1$k$,$k$0c-q2$k$,$k$0c-q4$k$,$k$0c-q5$k$,$k$0d-q1$k$,$k$0d-q5$k$,$k$1-0-q1$k$,$k$1-0-q2$k$,$k$1-0-q3$k$,$k$1-0-q4$k$,$k$1-0-q5$k$,$k$1-1-q1$k$,$k$1-1-q2$k$,$k$1-1-q3$k$,$k$1-1-q4$k$,$k$1-1-q5$k$,$k$1-2-q1$k$,$k$1-2-q2$k$,$k$1-2-q3$k$,$k$1-2-q4$k$,$k$1-2-q5$k$,$k$1-3-q1$k$,$k$1-3-q2$k$,$k$1-3-q3$k$,$k$1-3-q4$k$,$k$1-3-q5$k$,$k$2-0-q2$k$,$k$2-0-q3$k$,$k$2-0-q4$k$,$k$2-0-q5$k$,$k$2-1-q2$k$,$k$2-1-q3$k$,$k$2-1-q4$k$,$k$2-1-q5$k$,$k$2-2-q3$k$,$k$2-2-q5$k$,$k$2-3-q1$k$,$k$2-3-q2$k$,$k$2-3-q3$k$,$k$2-3-q4$k$,$k$2-3-q5$k$,$k$2-4-q2$k$,$k$2-4-q3$k$,$k$2-4-q4$k$,$k$2-4-q5$k$,$k$3-0-q1$k$,$k$3-0-q2$k$,$k$3-0-q3$k$,$k$3-0-q4$k$,$k$3-0-q5$k$,$k$3-1-q1$k$,$k$3-1-q2$k$,$k$3-1-q3$k$,$k$3-1-q4$k$,$k$3-1-q5$k$,$k$3-2-q1$k$,$k$3-2-q2$k$,$k$3-2-q3$k$,$k$3-2-q4$k$,$k$3-2-q5$k$,$k$3-3-q1$k$,$k$3-3-q2$k$,$k$3-3-q3$k$,$k$3-3-q4$k$,$k$3-3-q5$k$,$k$3-4-q1$k$,$k$3-4-q3$k$,$k$3-4-q4$k$,$k$3-4-q5$k$,$k$4-0-q1$k$,$k$4-0-q2$k$,$k$4-0-q3$k$,$k$4-0-q4$k$,$k$4-0-q5$k$,$k$4-1-q1$k$,$k$4-1-q2$k$,$k$4-1-q3$k$,$k$4-1-q4$k$,$k$4-1-q5$k$,$k$4-2-q2$k$,$k$4-2-q3$k$,$k$4-2-q4$k$,$k$4-2-q5$k$,$k$4-3-q1$k$,$k$4-3-q2$k$,$k$4-3-q3$k$,$k$4-3-q4$k$,$k$4-3-q5$k$,$k$b1-q2$k$,$k$b1-q3$k$,$k$b1-q4$k$,$k$b1-q5$k$,$k$b2-q1$k$,$k$b2-q2$k$,$k$b2-q3$k$,$k$b2-q4$k$,$k$b2-q5$k$,$k$b2-q6$k$,$k$u1-q1$k$,$k$u1-q2$k$,$k$u1-q3$k$,$k$u1-q4$k$,$k$u1-q5$k$,$k$u2-q1$k$,$k$u2-q2$k$,$k$u2-q3$k$,$k$u2-q4$k$,$k$u2-q5$k$,$k$u3-q1$k$,$k$u3-q2$k$,$k$u3-q3$k$,$k$u3-q4$k$,$k$u3-q5$k$,$k$u4-q1$k$,$k$u4-q2$k$,$k$u4-q3$k$,$k$u4-q4$k$,$k$u4-q5$k$);
